"use strict";
var _a;
Object.defineProperty(exports, "__esModule", { value: true });
exports.GithubWorkflow = void 0;
exports.createGitHubWorkflows = createGitHubWorkflows;
exports.saveWorkflowTemplates = saveWorkflowTemplates;
const JSII_RTTI_SYMBOL_1 = Symbol.for("jsii.rtti");
const fs = require("fs");
const path = require("path");
const yaml_1 = require("yaml");
const json_patch_1 = require("./utils/json-patch");
class GithubWorkflow {
    constructor(json) {
        this.json = json;
    }
    /**
     * Applies a set of JSON-Patch (RFC-6902) operations to this object and returns the result.
     * @param ops The operations to apply
     * @returns The result object
     */
    patch(...ops) {
        const jsonPatch = new json_patch_1.JsonPatch();
        const result = jsonPatch.patch({ ...this.json }, ...ops);
        this.json = result;
        return new GithubWorkflow(result);
    }
}
exports.GithubWorkflow = GithubWorkflow;
_a = JSII_RTTI_SYMBOL_1;
GithubWorkflow[_a] = { fqn: "agentl.GithubWorkflow", version: "0.0.0" };
const AUTO_GENERATED_COMMENT = '# ~~ Generated by cdk-express-pipeline. To modify, edit your pipeline and run `cdk synth`';
const CDK_EXPRESS_PIPELINE_GITHUB_DIFF_VERSION = '0.1.5';
function createGitHubWorkflows(githubConfig, waves) {
    const workflowFiles = [];
    workflowFiles.push(synthReusableAction(githubConfig.buildConfig));
    workflowFiles.push(diffReusableAction());
    workflowFiles.push(deployReusableAction(githubConfig.buildConfig));
    for (const diffConfig of githubConfig.diff) {
        const hasMultipleWorkflows = githubConfig.diff.length > 1;
        if (!diffConfig.id && hasMultipleWorkflows) {
            throw new Error('Diff workflow configuration must have an id');
        }
        workflowFiles.push(diffWorkflow(diffConfig, waves, hasMultipleWorkflows, githubConfig));
    }
    for (const deployConfig of githubConfig.deploy) {
        const hasMultipleWorkflows = githubConfig.deploy.length > 1;
        if (!deployConfig.id && hasMultipleWorkflows) {
            throw new Error('Deploy workflow configuration must have an id');
        }
        workflowFiles.push(deployWorkflow(deployConfig, waves, hasMultipleWorkflows, githubConfig));
    }
    return workflowFiles;
}
function saveWorkflowTemplates(templates, directory) {
    const githubDir = directory || path.join(process.cwd(), '.github');
    if (!fs.existsSync(githubDir)) {
        fs.mkdirSync(githubDir, { recursive: true });
    }
    templates.forEach(template => {
        const filePath = path.join(githubDir, template.fileName);
        const dirPath = path.dirname(filePath);
        if (!fs.existsSync(dirPath)) {
            fs.mkdirSync(dirPath, { recursive: true });
        }
        const yamlContent = `${AUTO_GENERATED_COMMENT}\n${(0, yaml_1.stringify)(template.content.json)}`;
        fs.writeFileSync(filePath, yamlContent);
    });
}
/**
 * Resolves CDK cloud assembly path relative to working directory
 */
function resolvePath(cloudAssemblyPath, workingDirectory) {
    if (!workingDirectory)
        return cloudAssemblyPath;
    // Only prepend if path is relative (not absolute)
    if (cloudAssemblyPath.startsWith('/') || cloudAssemblyPath.startsWith('.'))
        return cloudAssemblyPath;
    return `${workingDirectory}/${cloudAssemblyPath}`;
}
function synthReusableAction(buildConfig) {
    let buildSteps = [];
    if (buildConfig.type === 'preset-npm') {
        buildSteps = [{
                name: 'Set up node',
                uses: 'actions/setup-node@v4',
                with: {
                    'node-version': 20,
                    'cache': 'npm',
                },
            },
            {
                name: 'Install dependencies',
                run: 'npm ci',
                shell: 'bash',
            }];
    }
    else if (buildConfig.type === 'preset-pnpm') {
        buildSteps = [
            setupPnpmStep(),
            {
                name: 'Set up node',
                uses: 'actions/setup-node@v4',
                with: {
                    'node-version': 20,
                    'cache': 'pnpm',
                },
            },
            {
                name: 'Install dependencies',
                run: 'pnpm install --frozen-lockfile',
                shell: 'bash',
            },
        ];
    }
    else if (buildConfig.type === 'workflow') {
        if (!buildConfig.workflow?.path) {
            throw new Error('Workflow is required when using "workflow" type for build');
        }
        buildSteps = [
            {
                name: 'Build workflow',
                uses: buildConfig.workflow.path,
            },
        ];
    }
    const workflowContent = new GithubWorkflow({
        name: 'CDK Express Pipeline Synth Action',
        description: 'Run CDK synth for a specific stack pattern and post results to PR',
        inputs: {
            'command': {
                required: true,
                description: 'CDK synth command',
            },
            'cloud-assembly-directory': {
                required: true,
                description: 'The directory where the CDK cloud assembly should be synthesized to, must be the same as specified in the command',
            },
            'working-directory': {
                required: false,
                description: 'The subdirectory where CDK commands should run',
                default: '.',
            },
        },
        runs: {
            using: 'composite',
            steps: [
                {
                    name: 'Checkout repo',
                    uses: 'actions/checkout@v4',
                },
                ...buildSteps,
                {
                    'name': 'CDK Synth',
                    'shell': 'bash',
                    'working-directory': '${{ inputs.working-directory }}',
                    'run': '${{ inputs.command }}',
                },
                {
                    name: 'Cache Build',
                    uses: 'actions/cache/save@v4',
                    with: {
                        key: 'cache-build-${{ github.sha }}-${{ inputs.cloud-assembly-directory }}',
                        path: [
                            '${{ inputs.cloud-assembly-directory }}/',
                            'node_modules/',
                        ].join('\n'),
                    },
                },
            ],
        },
    });
    return {
        fileName: 'actions/cdk-express-pipeline-synth/action.yml',
        content: workflowContent,
    };
}
function diffReusableAction() {
    const workflowContent = new GithubWorkflow({
        name: 'CDK Diff Action',
        inputs: {
            'stack-selector-patterns': {
                required: true,
                description: 'The value of the {stackSelector} replacement in the command',
            },
            'command': {
                required: true,
                description: 'CDK diff command',
            },
            'cloud-assembly-directory': {
                required: true,
                description: 'The directory where the CDK cloud assembly is located',
            },
            'github-token': {
                required: true,
                description: 'GitHub token for posting comments',
            },
            'assume-role-arn': {
                required: true,
                description: 'The ARN of the role to assume for the deploy operation',
            },
            'assume-region': {
                required: true,
                description: 'The AWS region to assume for the deploy operation',
            },
            'job-name': {
                required: false,
                description: 'Name of the job, used to link to action/job logs in summaries',
            },
        },
        runs: {
            using: 'composite',
            steps: [
                restoreBuildCacheStep('${{ inputs.cloud-assembly-directory }}'),
                assumeAwsRoleStep('${{ inputs.assume-role-arn }}', '${{ inputs.assume-region }}'),
                {
                    name: 'CDK Diff Generate',
                    uses: 'rehanvdm/cdk-express-pipeline-github-diff@v' + CDK_EXPRESS_PIPELINE_GITHUB_DIFF_VERSION,
                    with: {
                        'mode': 'generate',
                        'cloud-assembly-directory': '${{ inputs.cloud-assembly-directory }}',
                        'stack-selectors': '${{ inputs.stack-selector-patterns }}',
                        'github-token': '${{ inputs.github-token }}',
                        'job-name': '${{ inputs.job-name }}',
                    },
                },
            ],
        },
    });
    return {
        fileName: 'actions/cdk-express-pipeline-diff/action.yml',
        content: workflowContent,
    };
}
function deployReusableAction(buildConfig) {
    const workflowContent = new GithubWorkflow({
        name: 'CDK Deploy Action',
        description: 'Run CDK deploy for a specific stack pattern',
        inputs: {
            'stack-selector-patterns': {
                required: true,
                description: 'The value of the {stackSelector} replacement in the command',
            },
            'command': {
                required: true,
                description: 'CDK deploy command',
            },
            'cloud-assembly-directory': {
                required: true,
                description: 'The directory where the CDK cloud assembly is located',
            },
            'assume-role-arn': {
                required: true,
                description: 'The ARN of the role to assume for the deploy operation',
            },
            'assume-region': {
                required: true,
                description: 'The AWS region to assume for the deploy operation',
            },
            'working-directory': {
                required: false,
                description: 'The subdirectory where CDK commands should run',
                default: '.',
            },
        },
        runs: {
            using: 'composite',
            steps: [
                restoreBuildCacheStep('${{ inputs.cloud-assembly-directory }}'),
                ...(buildConfig.type === 'preset-pnpm' ? [
                    setupPnpmStep(),
                    {
                        name: 'Install dependencies',
                        run: 'pnpm install --frozen-lockfile',
                        shell: 'bash',
                    },
                ] : []),
                assumeAwsRoleStep('${{ inputs.assume-role-arn }}', '${{ inputs.assume-region }}'),
                {
                    'name': 'CDK Deploy Command',
                    'working-directory': '${{ inputs.working-directory }}',
                    'run': '${{ inputs.command }}',
                    'shell': 'bash',
                },
            ],
        },
    });
    return {
        fileName: 'actions/cdk-express-pipeline-deploy/action.yml',
        content: workflowContent,
    };
}
function checkoutRepoStep() {
    return {
        name: 'Checkout repo',
        uses: 'actions/checkout@v4',
    };
}
function restoreBuildCacheStep(cloudAssemblyDir) {
    return {
        name: 'Restore Build Cache',
        uses: 'actions/cache/restore@v4',
        with: {
            key: `cache-build-$\{{ github.sha }}-${cloudAssemblyDir}`,
            path: [
                `${cloudAssemblyDir}/`,
                'node_modules/',
            ].join('\n'),
        },
    };
}
function assumeAwsRoleStep(assumeRoleArn, assumeRegion) {
    return {
        name: 'Configure AWS credentials',
        uses: 'aws-actions/configure-aws-credentials@v4',
        with: {
            'role-to-assume': assumeRoleArn,
            'aws-region': assumeRegion,
        },
    };
}
function setupPnpmStep() {
    return {
        name: 'Setup pnpm',
        uses: 'pnpm/action-setup@v4',
    };
}
function capitalizeFirstLetter(input) {
    if (!input)
        return '';
    return input.charAt(0).toUpperCase() + input.slice(1);
}
function extractArgument(command, argName) {
    const match = command.match(new RegExp(`${argName}(?:=|\\s)(?:"([^"]+)"|'([^']+)'|(\\S+))`));
    // Return whichever capturing group matched (double quotes, single quotes, or unquoted)
    return match ? (match[1] || match[2] || match[3]) : undefined;
}
function formatWorkflowTriggers(workflowTriggers) {
    let triggers = workflowTriggers;
    if (workflowTriggers.pullRequest) {
        // Need to change `pullRequest` to `pull_request` to match GitHub Actions syntax
        triggers = {
            ...workflowTriggers,
            pull_request: workflowTriggers.pullRequest,
        };
        delete triggers.pullRequest;
    }
    return triggers;
}
function diffWorkflow(diffConfig, waves, requiresUniqueId, githubConfig) {
    function toSnakeCase(str) {
        return str
            .replace(/([a-z])([A-Z])/g, '$1_$2') // handle camelCase or PascalCase
            .replace(/[\s\-]+/g, '_') // replace spaces and hyphens with underscores
            .replace(/([A-Z]+)/g, '_$1') // add underscores before uppercase sequences
            .replace(/^_+|_+$/g, '') // trim leading/trailing underscores
            .toLowerCase();
    }
    function stepStackSelectors(stackSelector) {
        const res = [];
        for (const wave of waves) {
            if (stackSelector === 'wave') {
                res.push({
                    name: toSnakeCase(wave.id),
                    selector: `${wave.id}${wave.separator}*`,
                });
            }
            else if (stackSelector === 'stage') {
                for (const stage of wave.stages) {
                    res.push({
                        name: toSnakeCase(wave.id + '__' + stage.id),
                        selector: `${wave.id}${wave.separator}${stage.id}${wave.separator}*`,
                    });
                }
            }
            else if (stackSelector === 'stack') {
                for (const stage of wave.stages) {
                    for (const stack of stage.stacks) {
                        res.push({
                            name: toSnakeCase(wave.id + '__' + stage.id + '__' + stack.id),
                            selector: stack.id,
                        });
                    }
                }
            }
        }
        return res;
    }
    const jobs = {};
    const printCloudAssemblies = [];
    for (let [commandKey, commandDiff] of Object.entries(diffConfig.commands)) {
        const cloudAssemblyDirSynth = extractArgument(commandDiff.synth, '--output') || 'cdk.out';
        const cloudAssemblyDir = extractArgument(commandDiff.diff, '--app') || 'cdk.out';
        if (cloudAssemblyDirSynth !== cloudAssemblyDir) {
            throw new Error('The --output argument of synth must be the same as the --app argument for diff');
        }
        // Get and resolve working directory
        const workingDirectory = diffConfig.workingDirectory || githubConfig?.workingDirectory;
        const resolvedCloudAssemblyDir = resolvePath(cloudAssemblyDir, workingDirectory);
        if (!commandDiff.diff.includes('{stackSelector}')) {
            throw new Error(`Command for diff workflow must include {stackSelector} placeholder, provided: ${commandDiff.diff}`);
        }
        const stackSelectors = stepStackSelectors(diffConfig.stackSelector);
        printCloudAssemblies.push({
            header: `CDK Diff - ${commandKey}`,
            directory: resolvedCloudAssemblyDir,
        });
        const matrixIncludes = [];
        for (const stackSelector of stackSelectors) {
            matrixIncludes.push({
                'job-name': `Diff ${commandKey} - ${stackSelector.name}`,
                'cloud-assembly-directory': resolvedCloudAssemblyDir,
                'stack-selector-patterns': stackSelector.selector,
                'command': commandDiff.diff.replace('{stackSelector}', stackSelector.selector),
                'assume-role-arn': diffConfig.assumeRoleArn,
                'assume-region': diffConfig.assumeRegion,
            });
        }
        // @ts-ignore
        jobs['synth__' + commandKey] = {
            'name': 'Synth ' + commandKey,
            'runs-on': 'ubuntu-latest',
            'steps': [
                checkoutRepoStep(),
                {
                    name: 'Run CDK Express Pipeline Synth',
                    uses: './.github/actions/cdk-express-pipeline-synth',
                    with: {
                        'command': commandDiff.synth,
                        'cloud-assembly-directory': resolvedCloudAssemblyDir,
                        'working-directory': workingDirectory || '.',
                    },
                },
            ],
        };
        // @ts-ignore
        jobs['diff__' + commandKey] = {
            'name': '${{ matrix.job-name }}',
            'needs': ['synth__' + commandKey],
            'runs-on': 'ubuntu-latest',
            'permissions': {
                'actions': 'write',
                'contents': 'write',
                'id-token': 'write',
                'pull-requests': 'write',
            },
            'strategy': {
                'matrix': {
                    include: matrixIncludes,
                },
                'fail-fast': false,
            },
            'steps': [
                checkoutRepoStep(),
                // restoreBuildCacheStep(),
                // assumeAwsRoleStep(diffConfig.assumeRoleArn, diffConfig.assumeRegion),
                {
                    name: 'Run CDK Express Pipeline Synth',
                    uses: './.github/actions/cdk-express-pipeline-diff',
                    with: {
                        'job-name': '${{ matrix.job-name }}',
                        'stack-selector-patterns': '${{ matrix.stack-selector-patterns }}',
                        'cloud-assembly-directory': '${{ matrix.cloud-assembly-directory }}',
                        'command': '${{ matrix.command }}',
                        'github-token': '${{ secrets.GITHUB_TOKEN }}',
                        'assume-role-arn': '${{ matrix.assume-role-arn }}',
                        'assume-region': '${{ matrix.assume-region }}',
                    },
                },
            ],
        };
    }
    const workflowContent = new GithubWorkflow({
        name: `CDK Express Pipeline Diff${(requiresUniqueId || diffConfig.id) ? ' - ' + capitalizeFirstLetter(diffConfig.id) : ''}`,
        on: formatWorkflowTriggers(diffConfig.on),
        jobs: {
            ...jobs,
            print_diff: {
                'name': 'Print Diff',
                'runs-on': 'ubuntu-latest',
                'permissions': {
                    'actions': 'write',
                    'contents': 'write',
                    'id-token': 'write',
                    'pull-requests': 'write',
                },
                'needs': Object.keys(jobs).filter(j => j.startsWith('diff__')),
                'steps': [
                    checkoutRepoStep(),
                    {
                        name: 'Update PR Description',
                        uses: 'rehanvdm/cdk-express-pipeline-github-diff@v' + CDK_EXPRESS_PIPELINE_GITHUB_DIFF_VERSION,
                        with: {
                            'mode': 'print',
                            'github-token': '${{ secrets.GITHUB_TOKEN }}',
                            'cloud-assemblies': JSON.stringify(printCloudAssemblies),
                        },
                    },
                ],
            },
        },
    });
    return {
        fileName: `workflows/cdk-express-pipeline-diff${(requiresUniqueId || diffConfig.id) ? '-' + diffConfig.id : ''}.yml`,
        content: workflowContent,
    };
}
function deployWorkflow(deployConfig, waves, requiresUniqueId, githubConfig) {
    function formatWaveJobId(wave, commandKey) {
        return `deploy__${commandKey}__${wave.id}`;
    }
    function formatStageJobId(stage, commandKey) {
        return `deploy__${commandKey}___${stage.wave.id}${stage.wave.separator}${stage.id}`;
    }
    function formatStackJobId(stack, commandKey) {
        return `deploy__${commandKey}___${stack.id}`;
    }
    const jobs = {};
    for (let [commandKey, commandDeploy] of Object.entries(deployConfig.commands)) {
        const cloudAssemblyDirSynth = extractArgument(commandDeploy.synth, '--output') || 'cdk.out';
        const cloudAssemblyDir = extractArgument(commandDeploy.deploy, '--app') || 'cdk.out';
        if (cloudAssemblyDirSynth !== cloudAssemblyDir) {
            throw new Error('The --output argument of synth must be the same as the --app argument for deploy');
        }
        if (!commandDeploy.deploy.includes('{stackSelector}')) {
            throw new Error(`Command for deploy workflow must include {stackSelector} placeholder, provided: ${commandDeploy.deploy}`);
        }
        // Get and resolve working directory
        const workingDirectory = deployConfig.workingDirectory || githubConfig?.workingDirectory;
        const resolvedCloudAssemblyDir = resolvePath(cloudAssemblyDir, workingDirectory);
        const synthJobId = 'synth__' + commandKey;
        // @ts-ignore
        jobs[synthJobId] = {
            'name': 'Synth ' + commandKey,
            'runs-on': 'ubuntu-latest',
            'steps': [
                checkoutRepoStep(),
                {
                    name: 'Run CDK Express Pipeline Synth',
                    uses: './.github/actions/cdk-express-pipeline-synth',
                    with: {
                        'command': commandDeploy.synth,
                        'cloud-assembly-directory': resolvedCloudAssemblyDir,
                        'working-directory': workingDirectory || '.',
                    },
                },
            ],
        };
        // Handle different deployment strategies based on stackSelector
        if (deployConfig.stackSelector === 'wave') {
            for (let w = 0; w < waves.length; w++) {
                const wave = waves[w];
                const waveJobId = formatWaveJobId(wave, commandKey);
                const needs = [];
                if (w == 0) {
                    needs.push(synthJobId);
                }
                else if (w > 0) {
                    const previousWaveJobId = formatWaveJobId(waves[w - 1], commandKey);
                    needs.push(previousWaveJobId);
                }
                // @ts-ignore
                jobs[waveJobId] = {
                    'name': `[${commandKey}] 🌊 ${wave.id}`,
                    'needs': needs,
                    'runs-on': 'ubuntu-latest',
                    'permissions': {
                        'actions': 'write',
                        'contents': 'write',
                        'id-token': 'write',
                    },
                    'steps': [
                        checkoutRepoStep(),
                        {
                            name: 'Run CDK Express Pipeline Deploy',
                            uses: './.github/actions/cdk-express-pipeline-deploy',
                            with: {
                                'stack-selector-patterns': `${wave.id}${wave.separator}*`,
                                'cloud-assembly-directory': resolvedCloudAssemblyDir,
                                'command': commandDeploy.deploy.replace('{stackSelector}', `${wave.id}${wave.separator}*`),
                                'assume-role-arn': deployConfig.assumeRoleArn,
                                'assume-region': deployConfig.assumeRegion,
                                'working-directory': workingDirectory || '.',
                            },
                        },
                    ],
                };
            }
        }
        else if (deployConfig.stackSelector === 'stage') {
            for (let w = 0; w < waves.length; w++) {
                const wave = waves[w];
                for (let s = 0; s < wave.stages.length; s++) {
                    const stage = wave.stages[s];
                    const stageJobId = formatStageJobId(stage, commandKey);
                    const needs = [];
                    if (w == 0) {
                        needs.push(synthJobId);
                    }
                    else if (w > 0) {
                        // Each stage job in this wave needs to depend on the previous wave's stage jobs
                        for (const sPrev of waves[w - 1].stages) {
                            needs.push(formatStageJobId(sPrev, commandKey));
                        }
                    }
                    if (wave.sequentialStages && s > 0) {
                        // Each stage job needs to depend on the previous stage job in the same wave
                        const previousStageJobId = formatStageJobId(wave.stages[s - 1], commandKey);
                        needs.push(previousStageJobId);
                    }
                    // @ts-ignore
                    jobs[stageJobId] = {
                        'name': `[${commandKey}] 🏗 ${wave.id}${wave.separator}${stage.id}`,
                        'needs': needs,
                        'runs-on': 'ubuntu-latest',
                        'permissions': {
                            'actions': 'write',
                            'contents': 'write',
                            'id-token': 'write',
                        },
                        'steps': [
                            checkoutRepoStep(),
                            {
                                name: 'Run CDK Express Pipeline Deploy',
                                uses: './.github/actions/cdk-express-pipeline-deploy',
                                with: {
                                    'stack-selector-patterns': `${wave.id}${wave.separator}${stage.id}${wave.separator}*`,
                                    'cloud-assembly-directory': resolvedCloudAssemblyDir,
                                    'command': commandDeploy.deploy.replace('{stackSelector}', `${wave.id}${wave.separator}${stage.id}${wave.separator}*`),
                                    'assume-role-arn': deployConfig.assumeRoleArn,
                                    'assume-region': deployConfig.assumeRegion,
                                    'working-directory': workingDirectory || '.',
                                },
                            },
                        ],
                    };
                }
            }
        }
        else if (deployConfig.stackSelector === 'stack') {
            for (let w = 0; w < waves.length; w++) {
                const wave = waves[w];
                for (let s = 0; s < wave.stages.length; s++) {
                    const stage = wave.stages[s];
                    for (let st = 0; st < stage.stacks.length; st++) {
                        const stack = stage.stacks[st];
                        const stackJobId = formatStackJobId(stack, commandKey);
                        const needs = [];
                        if (w == 0) {
                            needs.push(synthJobId);
                        }
                        else if (w > 0) {
                            // Each stack job in this wave needs to depend on the previous wave's stack jobs
                            for (const sPrev of waves[w - 1].stages) {
                                for (const stPrev of sPrev.stacks) {
                                    needs.push(formatStackJobId(stPrev, commandKey));
                                }
                            }
                        }
                        if (wave.sequentialStages && s > 0) {
                            // Each stack job needs to depend on the previous stage's stack jobs in the same wave
                            for (const stPrev of wave.stages[s - 1].stacks) {
                                needs.push(formatStackJobId(stPrev, commandKey));
                            }
                        }
                        // @ts-ignore
                        jobs[stackJobId] = {
                            'name': `[${commandKey}] 📦 ${stack.id}`,
                            'needs': needs,
                            'runs-on': 'ubuntu-latest',
                            'permissions': {
                                'actions': 'write',
                                'contents': 'write',
                                'id-token': 'write',
                            },
                            'steps': [
                                checkoutRepoStep(),
                                {
                                    name: 'Run CDK Express Pipeline Deploy',
                                    uses: './.github/actions/cdk-express-pipeline-deploy',
                                    with: {
                                        'stack-selector-patterns': stack.id,
                                        'cloud-assembly-directory': resolvedCloudAssemblyDir,
                                        'command': commandDeploy.deploy.replace('{stackSelector}', stack.id),
                                        'assume-role-arn': deployConfig.assumeRoleArn,
                                        'assume-region': deployConfig.assumeRegion,
                                        'working-directory': workingDirectory || '.',
                                    },
                                },
                            ],
                        };
                    }
                }
            }
        }
    }
    const workflowContent = new GithubWorkflow({
        name: `CDK Express Pipeline Deploy${(requiresUniqueId || deployConfig.id) ? ' - ' + capitalizeFirstLetter(deployConfig.id) : ''}`,
        concurrency: {
            'group': `cdk-express-pipeline-deploy${(requiresUniqueId || deployConfig.id) ? '-' + deployConfig.id : ''}`,
            'cancel-in-progress': false,
        },
        on: formatWorkflowTriggers(deployConfig.on),
        jobs: {
            ...jobs,
        },
    });
    return {
        fileName: `workflows/cdk-express-pipeline-deploy${(requiresUniqueId || deployConfig.id) ? '-' + deployConfig.id : ''}.yml`,
        content: workflowContent,
    };
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY2ktZ2l0aHViLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiLi4vc3JjL2NpLWdpdGh1Yi50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7O0FBMExBLHNEQTJCQztBQUVELHNEQWdCQzs7QUF2T0QseUJBQXlCO0FBQ3pCLDZCQUE2QjtBQUM3QiwrQkFBaUM7QUFJakMsbURBQXNEO0FBc0p0RCxNQUFhLGNBQWM7SUFJekIsWUFBWSxJQUFZO1FBQ3RCLElBQUksQ0FBQyxJQUFJLEdBQUcsSUFBSSxDQUFDO0lBQ25CLENBQUM7SUFFRDs7OztPQUlHO0lBQ0ksS0FBSyxDQUFDLEdBQUcsR0FBWTtRQUMxQixNQUFNLFNBQVMsR0FBRyxJQUFJLHNCQUFTLEVBQUUsQ0FBQztRQUNsQyxNQUFNLE1BQU0sR0FBRyxTQUFTLENBQUMsS0FBSyxDQUFDLEVBQUUsR0FBRyxJQUFJLENBQUMsSUFBSSxFQUFFLEVBQUUsR0FBRyxHQUFHLENBQUMsQ0FBQztRQUN6RCxJQUFJLENBQUMsSUFBSSxHQUFHLE1BQU0sQ0FBQztRQUNuQixPQUFPLElBQUksY0FBYyxDQUFDLE1BQU0sQ0FBQyxDQUFDO0lBQ3BDLENBQUM7O0FBbEJILHdDQW1CQzs7O0FBUUQsTUFBTSxzQkFBc0IsR0FBRywyRkFBMkYsQ0FBQztBQUMzSCxNQUFNLHdDQUF3QyxHQUFHLE9BQU8sQ0FBQztBQUV6RCxTQUFnQixxQkFBcUIsQ0FBQyxZQUFrQyxFQUFFLEtBQXFCO0lBRTdGLE1BQU0sYUFBYSxHQUF5QixFQUFFLENBQUM7SUFDL0MsYUFBYSxDQUFDLElBQUksQ0FBQyxtQkFBbUIsQ0FBQyxZQUFZLENBQUMsV0FBVyxDQUFDLENBQUMsQ0FBQztJQUNsRSxhQUFhLENBQUMsSUFBSSxDQUFDLGtCQUFrQixFQUFFLENBQUMsQ0FBQztJQUN6QyxhQUFhLENBQUMsSUFBSSxDQUFDLG9CQUFvQixDQUFDLFlBQVksQ0FBQyxXQUFXLENBQUMsQ0FBQyxDQUFDO0lBR25FLEtBQUssTUFBTSxVQUFVLElBQUksWUFBWSxDQUFDLElBQUksRUFBRSxDQUFDO1FBQzNDLE1BQU0sb0JBQW9CLEdBQUcsWUFBWSxDQUFDLElBQUksQ0FBQyxNQUFNLEdBQUcsQ0FBQyxDQUFDO1FBQzFELElBQUksQ0FBQyxVQUFVLENBQUMsRUFBRSxJQUFJLG9CQUFvQixFQUFFLENBQUM7WUFDM0MsTUFBTSxJQUFJLEtBQUssQ0FBQyw2Q0FBNkMsQ0FBQyxDQUFDO1FBQ2pFLENBQUM7UUFFRCxhQUFhLENBQUMsSUFBSSxDQUFDLFlBQVksQ0FBQyxVQUFVLEVBQUUsS0FBSyxFQUFFLG9CQUFvQixFQUFFLFlBQVksQ0FBQyxDQUFDLENBQUM7SUFDMUYsQ0FBQztJQUVELEtBQUssTUFBTSxZQUFZLElBQUksWUFBWSxDQUFDLE1BQU0sRUFBRSxDQUFDO1FBQy9DLE1BQU0sb0JBQW9CLEdBQUcsWUFBWSxDQUFDLE1BQU0sQ0FBQyxNQUFNLEdBQUcsQ0FBQyxDQUFDO1FBQzVELElBQUksQ0FBQyxZQUFZLENBQUMsRUFBRSxJQUFJLG9CQUFvQixFQUFFLENBQUM7WUFDN0MsTUFBTSxJQUFJLEtBQUssQ0FBQywrQ0FBK0MsQ0FBQyxDQUFDO1FBQ25FLENBQUM7UUFFRCxhQUFhLENBQUMsSUFBSSxDQUFDLGNBQWMsQ0FBQyxZQUFZLEVBQUUsS0FBSyxFQUFFLG9CQUFvQixFQUFFLFlBQVksQ0FBQyxDQUFDLENBQUM7SUFDOUYsQ0FBQztJQUVELE9BQU8sYUFBYSxDQUFDO0FBQ3ZCLENBQUM7QUFFRCxTQUFnQixxQkFBcUIsQ0FBQyxTQUErQixFQUFFLFNBQWtCO0lBQ3ZGLE1BQU0sU0FBUyxHQUFHLFNBQVMsSUFBSSxJQUFJLENBQUMsSUFBSSxDQUFDLE9BQU8sQ0FBQyxHQUFHLEVBQUUsRUFBRSxTQUFTLENBQUMsQ0FBQztJQUNuRSxJQUFJLENBQUMsRUFBRSxDQUFDLFVBQVUsQ0FBQyxTQUFTLENBQUMsRUFBRSxDQUFDO1FBQzlCLEVBQUUsQ0FBQyxTQUFTLENBQUMsU0FBUyxFQUFFLEVBQUUsU0FBUyxFQUFFLElBQUksRUFBRSxDQUFDLENBQUM7SUFDL0MsQ0FBQztJQUVELFNBQVMsQ0FBQyxPQUFPLENBQUMsUUFBUSxDQUFDLEVBQUU7UUFDM0IsTUFBTSxRQUFRLEdBQUcsSUFBSSxDQUFDLElBQUksQ0FBQyxTQUFTLEVBQUUsUUFBUSxDQUFDLFFBQVEsQ0FBQyxDQUFDO1FBQ3pELE1BQU0sT0FBTyxHQUFHLElBQUksQ0FBQyxPQUFPLENBQUMsUUFBUSxDQUFDLENBQUM7UUFDdkMsSUFBSSxDQUFDLEVBQUUsQ0FBQyxVQUFVLENBQUMsT0FBTyxDQUFDLEVBQUUsQ0FBQztZQUM1QixFQUFFLENBQUMsU0FBUyxDQUFDLE9BQU8sRUFBRSxFQUFFLFNBQVMsRUFBRSxJQUFJLEVBQUUsQ0FBQyxDQUFDO1FBQzdDLENBQUM7UUFFRCxNQUFNLFdBQVcsR0FBRyxHQUFHLHNCQUFzQixLQUFLLElBQUEsZ0JBQVMsRUFBQyxRQUFRLENBQUMsT0FBTyxDQUFDLElBQUksQ0FBQyxFQUFFLENBQUM7UUFDckYsRUFBRSxDQUFDLGFBQWEsQ0FBQyxRQUFRLEVBQUUsV0FBVyxDQUFDLENBQUM7SUFDMUMsQ0FBQyxDQUFDLENBQUM7QUFDTCxDQUFDO0FBRUQ7O0dBRUc7QUFDSCxTQUFTLFdBQVcsQ0FBQyxpQkFBeUIsRUFBRSxnQkFBeUI7SUFDdkUsSUFBSSxDQUFDLGdCQUFnQjtRQUFFLE9BQU8saUJBQWlCLENBQUM7SUFDaEQsa0RBQWtEO0lBQ2xELElBQUksaUJBQWlCLENBQUMsVUFBVSxDQUFDLEdBQUcsQ0FBQyxJQUFJLGlCQUFpQixDQUFDLFVBQVUsQ0FBQyxHQUFHLENBQUM7UUFBRSxPQUFPLGlCQUFpQixDQUFDO0lBQ3JHLE9BQU8sR0FBRyxnQkFBZ0IsSUFBSSxpQkFBaUIsRUFBRSxDQUFDO0FBQ3BELENBQUM7QUFFRCxTQUFTLG1CQUFtQixDQUFDLFdBQWdDO0lBQzNELElBQUksVUFBVSxHQUFhLEVBQUUsQ0FBQztJQUM5QixJQUFJLFdBQVcsQ0FBQyxJQUFJLEtBQUssWUFBWSxFQUFFLENBQUM7UUFDdEMsVUFBVSxHQUFHLENBQUM7Z0JBQ1osSUFBSSxFQUFFLGFBQWE7Z0JBQ25CLElBQUksRUFBRSx1QkFBdUI7Z0JBQzdCLElBQUksRUFBRTtvQkFDSixjQUFjLEVBQUUsRUFBRTtvQkFDbEIsT0FBTyxFQUFFLEtBQUs7aUJBQ2Y7YUFDRjtZQUNEO2dCQUNFLElBQUksRUFBRSxzQkFBc0I7Z0JBQzVCLEdBQUcsRUFBRSxRQUFRO2dCQUNiLEtBQUssRUFBRSxNQUFNO2FBQ2QsQ0FBQyxDQUFDO0lBQ0wsQ0FBQztTQUFNLElBQUksV0FBVyxDQUFDLElBQUksS0FBSyxhQUFhLEVBQUUsQ0FBQztRQUM5QyxVQUFVLEdBQUc7WUFDWCxhQUFhLEVBQUU7WUFDZjtnQkFDRSxJQUFJLEVBQUUsYUFBYTtnQkFDbkIsSUFBSSxFQUFFLHVCQUF1QjtnQkFDN0IsSUFBSSxFQUFFO29CQUNKLGNBQWMsRUFBRSxFQUFFO29CQUNsQixPQUFPLEVBQUUsTUFBTTtpQkFDaEI7YUFDRjtZQUNEO2dCQUNFLElBQUksRUFBRSxzQkFBc0I7Z0JBQzVCLEdBQUcsRUFBRSxnQ0FBZ0M7Z0JBQ3JDLEtBQUssRUFBRSxNQUFNO2FBQ2Q7U0FDRixDQUFDO0lBQ0osQ0FBQztTQUFNLElBQUksV0FBVyxDQUFDLElBQUksS0FBSyxVQUFVLEVBQUUsQ0FBQztRQUMzQyxJQUFJLENBQUMsV0FBVyxDQUFDLFFBQVEsRUFBRSxJQUFJLEVBQUUsQ0FBQztZQUNoQyxNQUFNLElBQUksS0FBSyxDQUFDLDJEQUEyRCxDQUFDLENBQUM7UUFDL0UsQ0FBQztRQUNELFVBQVUsR0FBRztZQUNYO2dCQUNFLElBQUksRUFBRSxnQkFBZ0I7Z0JBQ3RCLElBQUksRUFBRSxXQUFXLENBQUMsUUFBUSxDQUFDLElBQUk7YUFDaEM7U0FDRixDQUFDO0lBQ0osQ0FBQztJQUVELE1BQU0sZUFBZSxHQUFHLElBQUksY0FBYyxDQUFDO1FBQ3pDLElBQUksRUFBRSxtQ0FBbUM7UUFDekMsV0FBVyxFQUFFLG1FQUFtRTtRQUNoRixNQUFNLEVBQUU7WUFDTixTQUFTLEVBQUU7Z0JBQ1QsUUFBUSxFQUFFLElBQUk7Z0JBQ2QsV0FBVyxFQUFFLG1CQUFtQjthQUNqQztZQUNELDBCQUEwQixFQUFFO2dCQUMxQixRQUFRLEVBQUUsSUFBSTtnQkFDZCxXQUFXLEVBQUUsbUhBQW1IO2FBQ2pJO1lBQ0QsbUJBQW1CLEVBQUU7Z0JBQ25CLFFBQVEsRUFBRSxLQUFLO2dCQUNmLFdBQVcsRUFBRSxnREFBZ0Q7Z0JBQzdELE9BQU8sRUFBRSxHQUFHO2FBQ2I7U0FDRjtRQUNELElBQUksRUFBRTtZQUNKLEtBQUssRUFBRSxXQUFXO1lBQ2xCLEtBQUssRUFBRTtnQkFDTDtvQkFDRSxJQUFJLEVBQUUsZUFBZTtvQkFDckIsSUFBSSxFQUFFLHFCQUFxQjtpQkFDNUI7Z0JBQ0QsR0FBRyxVQUFVO2dCQUNiO29CQUNFLE1BQU0sRUFBRSxXQUFXO29CQUNuQixPQUFPLEVBQUUsTUFBTTtvQkFDZixtQkFBbUIsRUFBRSxpQ0FBaUM7b0JBQ3RELEtBQUssRUFBRSx1QkFBdUI7aUJBQy9CO2dCQUNEO29CQUNFLElBQUksRUFBRSxhQUFhO29CQUNuQixJQUFJLEVBQUUsdUJBQXVCO29CQUM3QixJQUFJLEVBQUU7d0JBQ0osR0FBRyxFQUFFLHNFQUFzRTt3QkFDM0UsSUFBSSxFQUFFOzRCQUNKLHlDQUF5Qzs0QkFDekMsZUFBZTt5QkFDaEIsQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDO3FCQUNiO2lCQUNGO2FBQ0Y7U0FDRjtLQUNGLENBQUMsQ0FBQztJQUVILE9BQU87UUFDTCxRQUFRLEVBQUUsK0NBQStDO1FBQ3pELE9BQU8sRUFBRSxlQUFlO0tBQ3pCLENBQUM7QUFDSixDQUFDO0FBQ0QsU0FBUyxrQkFBa0I7SUFDekIsTUFBTSxlQUFlLEdBQUcsSUFBSSxjQUFjLENBQUM7UUFDekMsSUFBSSxFQUFFLGlCQUFpQjtRQUN2QixNQUFNLEVBQUU7WUFDTix5QkFBeUIsRUFBRTtnQkFDekIsUUFBUSxFQUFFLElBQUk7Z0JBQ2QsV0FBVyxFQUFFLDZEQUE2RDthQUMzRTtZQUNELFNBQVMsRUFBRTtnQkFDVCxRQUFRLEVBQUUsSUFBSTtnQkFDZCxXQUFXLEVBQUUsa0JBQWtCO2FBQ2hDO1lBQ0QsMEJBQTBCLEVBQUU7Z0JBQzFCLFFBQVEsRUFBRSxJQUFJO2dCQUNkLFdBQVcsRUFBRSx1REFBdUQ7YUFDckU7WUFDRCxjQUFjLEVBQUU7Z0JBQ2QsUUFBUSxFQUFFLElBQUk7Z0JBQ2QsV0FBVyxFQUFFLG1DQUFtQzthQUNqRDtZQUNELGlCQUFpQixFQUFFO2dCQUNqQixRQUFRLEVBQUUsSUFBSTtnQkFDZCxXQUFXLEVBQUUsd0RBQXdEO2FBQ3RFO1lBQ0QsZUFBZSxFQUFFO2dCQUNmLFFBQVEsRUFBRSxJQUFJO2dCQUNkLFdBQVcsRUFBRSxtREFBbUQ7YUFDakU7WUFDRCxVQUFVLEVBQUU7Z0JBQ1YsUUFBUSxFQUFFLEtBQUs7Z0JBQ2YsV0FBVyxFQUFFLCtEQUErRDthQUM3RTtTQUNGO1FBQ0QsSUFBSSxFQUFFO1lBQ0osS0FBSyxFQUFFLFdBQVc7WUFDbEIsS0FBSyxFQUFFO2dCQUNMLHFCQUFxQixDQUFDLHdDQUF3QyxDQUFDO2dCQUMvRCxpQkFBaUIsQ0FBQywrQkFBK0IsRUFBRSw2QkFBNkIsQ0FBQztnQkFDakY7b0JBQ0UsSUFBSSxFQUFFLG1CQUFtQjtvQkFDekIsSUFBSSxFQUFFLDZDQUE2QyxHQUFDLHdDQUF3QztvQkFDNUYsSUFBSSxFQUFFO3dCQUNKLE1BQU0sRUFBRSxVQUFVO3dCQUNsQiwwQkFBMEIsRUFBRSx3Q0FBd0M7d0JBQ3BFLGlCQUFpQixFQUFFLHVDQUF1Qzt3QkFDMUQsY0FBYyxFQUFFLDRCQUE0Qjt3QkFDNUMsVUFBVSxFQUFFLHdCQUF3QjtxQkFDckM7aUJBQ0Y7YUFDRjtTQUNGO0tBQ0YsQ0FBQyxDQUFDO0lBRUgsT0FBTztRQUNMLFFBQVEsRUFBRSw4Q0FBOEM7UUFDeEQsT0FBTyxFQUFFLGVBQWU7S0FDekIsQ0FBQztBQUNKLENBQUM7QUFDRCxTQUFTLG9CQUFvQixDQUFDLFdBQWdDO0lBQzVELE1BQU0sZUFBZSxHQUFHLElBQUksY0FBYyxDQUFDO1FBQ3pDLElBQUksRUFBRSxtQkFBbUI7UUFDekIsV0FBVyxFQUFFLDZDQUE2QztRQUMxRCxNQUFNLEVBQUU7WUFDTix5QkFBeUIsRUFBRTtnQkFDekIsUUFBUSxFQUFFLElBQUk7Z0JBQ2QsV0FBVyxFQUFFLDZEQUE2RDthQUMzRTtZQUNELFNBQVMsRUFBRTtnQkFDVCxRQUFRLEVBQUUsSUFBSTtnQkFDZCxXQUFXLEVBQUUsb0JBQW9CO2FBQ2xDO1lBQ0QsMEJBQTBCLEVBQUU7Z0JBQzFCLFFBQVEsRUFBRSxJQUFJO2dCQUNkLFdBQVcsRUFBRSx1REFBdUQ7YUFDckU7WUFDRCxpQkFBaUIsRUFBRTtnQkFDakIsUUFBUSxFQUFFLElBQUk7Z0JBQ2QsV0FBVyxFQUFFLHdEQUF3RDthQUN0RTtZQUNELGVBQWUsRUFBRTtnQkFDZixRQUFRLEVBQUUsSUFBSTtnQkFDZCxXQUFXLEVBQUUsbURBQW1EO2FBQ2pFO1lBQ0QsbUJBQW1CLEVBQUU7Z0JBQ25CLFFBQVEsRUFBRSxLQUFLO2dCQUNmLFdBQVcsRUFBRSxnREFBZ0Q7Z0JBQzdELE9BQU8sRUFBRSxHQUFHO2FBQ2I7U0FDRjtRQUNELElBQUksRUFBRTtZQUNKLEtBQUssRUFBRSxXQUFXO1lBQ2xCLEtBQUssRUFBRTtnQkFDTCxxQkFBcUIsQ0FBQyx3Q0FBd0MsQ0FBQztnQkFDL0QsR0FBRyxDQUFDLFdBQVcsQ0FBQyxJQUFJLEtBQUssYUFBYSxDQUFDLENBQUMsQ0FBQztvQkFDdkMsYUFBYSxFQUFFO29CQUNmO3dCQUNFLElBQUksRUFBRSxzQkFBc0I7d0JBQzVCLEdBQUcsRUFBRSxnQ0FBZ0M7d0JBQ3JDLEtBQUssRUFBRSxNQUFNO3FCQUNkO2lCQUNGLENBQUMsQ0FBQyxDQUFDLEVBQUUsQ0FBQztnQkFDUCxpQkFBaUIsQ0FBQywrQkFBK0IsRUFBRSw2QkFBNkIsQ0FBQztnQkFDakY7b0JBQ0UsTUFBTSxFQUFFLG9CQUFvQjtvQkFDNUIsbUJBQW1CLEVBQUUsaUNBQWlDO29CQUN0RCxLQUFLLEVBQUUsdUJBQXVCO29CQUM5QixPQUFPLEVBQUUsTUFBTTtpQkFDaEI7YUFDRjtTQUNGO0tBQ0YsQ0FBQyxDQUFDO0lBRUgsT0FBTztRQUNMLFFBQVEsRUFBRSxnREFBZ0Q7UUFDMUQsT0FBTyxFQUFFLGVBQWU7S0FDekIsQ0FBQztBQUNKLENBQUM7QUFHRCxTQUFTLGdCQUFnQjtJQUN2QixPQUFPO1FBQ0wsSUFBSSxFQUFFLGVBQWU7UUFDckIsSUFBSSxFQUFFLHFCQUFxQjtLQUM1QixDQUFDO0FBQ0osQ0FBQztBQUNELFNBQVMscUJBQXFCLENBQUMsZ0JBQXdCO0lBQ3JELE9BQU87UUFDTCxJQUFJLEVBQUUscUJBQXFCO1FBQzNCLElBQUksRUFBRSwwQkFBMEI7UUFDaEMsSUFBSSxFQUFFO1lBQ0osR0FBRyxFQUFFLGtDQUFrQyxnQkFBZ0IsRUFBRTtZQUN6RCxJQUFJLEVBQUU7Z0JBQ0osR0FBRyxnQkFBZ0IsR0FBRztnQkFDdEIsZUFBZTthQUNoQixDQUFDLElBQUksQ0FBQyxJQUFJLENBQUM7U0FDYjtLQUNGLENBQUM7QUFDSixDQUFDO0FBQ0QsU0FBUyxpQkFBaUIsQ0FBQyxhQUFxQixFQUFFLFlBQW9CO0lBQ3BFLE9BQU87UUFDTCxJQUFJLEVBQUUsMkJBQTJCO1FBQ2pDLElBQUksRUFBRSwwQ0FBMEM7UUFDaEQsSUFBSSxFQUFFO1lBQ0osZ0JBQWdCLEVBQUUsYUFBYTtZQUMvQixZQUFZLEVBQUUsWUFBWTtTQUMzQjtLQUNGLENBQUM7QUFDSixDQUFDO0FBQ0QsU0FBUyxhQUFhO0lBQ3BCLE9BQU87UUFDTCxJQUFJLEVBQUUsWUFBWTtRQUNsQixJQUFJLEVBQUUsc0JBQXNCO0tBQzdCLENBQUM7QUFDSixDQUFDO0FBRUQsU0FBUyxxQkFBcUIsQ0FBQyxLQUFhO0lBQzFDLElBQUksQ0FBQyxLQUFLO1FBQUUsT0FBTyxFQUFFLENBQUM7SUFDdEIsT0FBTyxLQUFLLENBQUMsTUFBTSxDQUFDLENBQUMsQ0FBQyxDQUFDLFdBQVcsRUFBRSxHQUFHLEtBQUssQ0FBQyxLQUFLLENBQUMsQ0FBQyxDQUFDLENBQUM7QUFDeEQsQ0FBQztBQUdELFNBQVMsZUFBZSxDQUFDLE9BQWUsRUFBRSxPQUFlO0lBQ3ZELE1BQU0sS0FBSyxHQUFHLE9BQU8sQ0FBQyxLQUFLLENBQUMsSUFBSSxNQUFNLENBQUMsR0FBRyxPQUFPLHlDQUF5QyxDQUFDLENBQUMsQ0FBQztJQUM3Rix1RkFBdUY7SUFDdkYsT0FBTyxLQUFLLENBQUMsQ0FBQyxDQUFDLENBQUMsS0FBSyxDQUFDLENBQUMsQ0FBQyxJQUFJLEtBQUssQ0FBQyxDQUFDLENBQUMsSUFBSSxLQUFLLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsU0FBUyxDQUFDO0FBQ2hFLENBQUM7QUFFRCxTQUFTLHNCQUFzQixDQUFDLGdCQUFrQztJQUNoRSxJQUFJLFFBQVEsR0FBUSxnQkFBZ0IsQ0FBQztJQUNyQyxJQUFJLGdCQUFnQixDQUFDLFdBQVcsRUFBRSxDQUFDO1FBQ2pDLGdGQUFnRjtRQUNoRixRQUFRLEdBQUc7WUFDVCxHQUFHLGdCQUFnQjtZQUNuQixZQUFZLEVBQUUsZ0JBQWdCLENBQUMsV0FBVztTQUMzQyxDQUFDO1FBQ0YsT0FBTyxRQUFRLENBQUMsV0FBVyxDQUFDO0lBQzlCLENBQUM7SUFDRCxPQUFPLFFBQVEsQ0FBQztBQUNsQixDQUFDO0FBQ0QsU0FBUyxZQUFZLENBQUMsVUFBOEIsRUFBRSxLQUFxQixFQUN6RSxnQkFBeUIsRUFBRSxZQUFtQztJQUU5RCxTQUFTLFdBQVcsQ0FBQyxHQUFXO1FBQzlCLE9BQU8sR0FBRzthQUNQLE9BQU8sQ0FBQyxpQkFBaUIsRUFBRSxPQUFPLENBQUMsQ0FBQyxpQ0FBaUM7YUFDckUsT0FBTyxDQUFDLFVBQVUsRUFBRSxHQUFHLENBQUMsQ0FBQyw4Q0FBOEM7YUFDdkUsT0FBTyxDQUFDLFdBQVcsRUFBRSxLQUFLLENBQUMsQ0FBQyw2Q0FBNkM7YUFDekUsT0FBTyxDQUFDLFVBQVUsRUFBRSxFQUFFLENBQUMsQ0FBQyxvQ0FBb0M7YUFDNUQsV0FBVyxFQUFFLENBQUM7SUFDbkIsQ0FBQztJQUNELFNBQVMsa0JBQWtCLENBQUMsYUFBeUM7UUFDbkUsTUFBTSxHQUFHLEdBQXlDLEVBQUUsQ0FBQztRQUNyRCxLQUFLLE1BQU0sSUFBSSxJQUFJLEtBQUssRUFBRSxDQUFDO1lBQ3pCLElBQUksYUFBYSxLQUFLLE1BQU0sRUFBRSxDQUFDO2dCQUM3QixHQUFHLENBQUMsSUFBSSxDQUFDO29CQUNQLElBQUksRUFBRSxXQUFXLENBQUMsSUFBSSxDQUFDLEVBQUUsQ0FBQztvQkFDMUIsUUFBUSxFQUFFLEdBQUcsSUFBSSxDQUFDLEVBQUUsR0FBRyxJQUFJLENBQUMsU0FBUyxHQUFHO2lCQUN6QyxDQUFDLENBQUM7WUFDTCxDQUFDO2lCQUFNLElBQUksYUFBYSxLQUFLLE9BQU8sRUFBRSxDQUFDO2dCQUNyQyxLQUFLLE1BQU0sS0FBSyxJQUFJLElBQUksQ0FBQyxNQUFNLEVBQUUsQ0FBQztvQkFDaEMsR0FBRyxDQUFDLElBQUksQ0FBQzt3QkFDUCxJQUFJLEVBQUUsV0FBVyxDQUFDLElBQUksQ0FBQyxFQUFFLEdBQUcsSUFBSSxHQUFHLEtBQUssQ0FBQyxFQUFFLENBQUM7d0JBQzVDLFFBQVEsRUFBRSxHQUFHLElBQUksQ0FBQyxFQUFFLEdBQUcsSUFBSSxDQUFDLFNBQVMsR0FBRyxLQUFLLENBQUMsRUFBRSxHQUFHLElBQUksQ0FBQyxTQUFTLEdBQUc7cUJBQ3JFLENBQUMsQ0FBQztnQkFDTCxDQUFDO1lBQ0gsQ0FBQztpQkFBTSxJQUFJLGFBQWEsS0FBSyxPQUFPLEVBQUUsQ0FBQztnQkFDckMsS0FBSyxNQUFNLEtBQUssSUFBSSxJQUFJLENBQUMsTUFBTSxFQUFFLENBQUM7b0JBQ2hDLEtBQUssTUFBTSxLQUFLLElBQUksS0FBSyxDQUFDLE1BQU0sRUFBRSxDQUFDO3dCQUNqQyxHQUFHLENBQUMsSUFBSSxDQUFDOzRCQUNQLElBQUksRUFBRSxXQUFXLENBQUMsSUFBSSxDQUFDLEVBQUUsR0FBRyxJQUFJLEdBQUcsS0FBSyxDQUFDLEVBQUUsR0FBRyxJQUFJLEdBQUcsS0FBSyxDQUFDLEVBQUUsQ0FBQzs0QkFDOUQsUUFBUSxFQUFFLEtBQUssQ0FBQyxFQUFFO3lCQUNuQixDQUFDLENBQUM7b0JBQ0wsQ0FBQztnQkFDSCxDQUFDO1lBQ0gsQ0FBQztRQUNILENBQUM7UUFDRCxPQUFPLEdBQUcsQ0FBQztJQUNiLENBQUM7SUFHRCxNQUFNLElBQUksR0FBRyxFQUFFLENBQUM7SUFDaEIsTUFBTSxvQkFBb0IsR0FHcEIsRUFBRSxDQUFDO0lBQ1QsS0FBSyxJQUFJLENBQUMsVUFBVSxFQUFFLFdBQVcsQ0FBQyxJQUFJLE1BQU0sQ0FBQyxPQUFPLENBQUMsVUFBVSxDQUFDLFFBQVEsQ0FBQyxFQUFFLENBQUM7UUFDMUUsTUFBTSxxQkFBcUIsR0FBRyxlQUFlLENBQUMsV0FBVyxDQUFDLEtBQUssRUFBRSxVQUFVLENBQUMsSUFBSSxTQUFTLENBQUM7UUFDMUYsTUFBTSxnQkFBZ0IsR0FBRyxlQUFlLENBQUMsV0FBVyxDQUFDLElBQUksRUFBRSxPQUFPLENBQUMsSUFBSSxTQUFTLENBQUM7UUFDakYsSUFBSSxxQkFBcUIsS0FBSyxnQkFBZ0IsRUFBRSxDQUFDO1lBQy9DLE1BQU0sSUFBSSxLQUFLLENBQUMsZ0ZBQWdGLENBQUMsQ0FBQztRQUNwRyxDQUFDO1FBRUQsb0NBQW9DO1FBQ3BDLE1BQU0sZ0JBQWdCLEdBQUcsVUFBVSxDQUFDLGdCQUFnQixJQUFJLFlBQVksRUFBRSxnQkFBZ0IsQ0FBQztRQUN2RixNQUFNLHdCQUF3QixHQUFHLFdBQVcsQ0FBQyxnQkFBZ0IsRUFBRSxnQkFBZ0IsQ0FBQyxDQUFDO1FBRWpGLElBQUksQ0FBQyxXQUFXLENBQUMsSUFBSSxDQUFDLFFBQVEsQ0FBQyxpQkFBaUIsQ0FBQyxFQUFFLENBQUM7WUFDbEQsTUFBTSxJQUFJLEtBQUssQ0FBQyxpRkFBaUYsV0FBVyxDQUFDLElBQUksRUFBRSxDQUFDLENBQUM7UUFDdkgsQ0FBQztRQUNELE1BQU0sY0FBYyxHQUFHLGtCQUFrQixDQUFDLFVBQVUsQ0FBQyxhQUFhLENBQUMsQ0FBQztRQUVwRSxvQkFBb0IsQ0FBQyxJQUFJLENBQUM7WUFDeEIsTUFBTSxFQUFFLGNBQWMsVUFBVSxFQUFFO1lBQ2xDLFNBQVMsRUFBRSx3QkFBd0I7U0FDcEMsQ0FBQyxDQUFDO1FBQ0gsTUFBTSxjQUFjLEdBT2QsRUFBRSxDQUFDO1FBQ1QsS0FBSyxNQUFNLGFBQWEsSUFBSSxjQUFjLEVBQUUsQ0FBQztZQUMzQyxjQUFjLENBQUMsSUFBSSxDQUFDO2dCQUNsQixVQUFVLEVBQUUsUUFBUSxVQUFVLE1BQU0sYUFBYSxDQUFDLElBQUksRUFBRTtnQkFDeEQsMEJBQTBCLEVBQUUsd0JBQXdCO2dCQUNwRCx5QkFBeUIsRUFBRSxhQUFhLENBQUMsUUFBUTtnQkFDakQsU0FBUyxFQUFFLFdBQVcsQ0FBQyxJQUFJLENBQUMsT0FBTyxDQUFDLGlCQUFpQixFQUFFLGFBQWEsQ0FBQyxRQUFRLENBQUM7Z0JBQzlFLGlCQUFpQixFQUFFLFVBQVUsQ0FBQyxhQUFhO2dCQUMzQyxlQUFlLEVBQUUsVUFBVSxDQUFDLFlBQVk7YUFDekMsQ0FBQyxDQUFDO1FBQ0wsQ0FBQztRQUVELGFBQWE7UUFDYixJQUFJLENBQUMsU0FBUyxHQUFHLFVBQVUsQ0FBQyxHQUFHO1lBQzdCLE1BQU0sRUFBRSxRQUFRLEdBQUcsVUFBVTtZQUM3QixTQUFTLEVBQUUsZUFBZTtZQUMxQixPQUFPLEVBQUU7Z0JBQ1AsZ0JBQWdCLEVBQUU7Z0JBQ2xCO29CQUNFLElBQUksRUFBRSxnQ0FBZ0M7b0JBQ3RDLElBQUksRUFBRSw4Q0FBOEM7b0JBQ3BELElBQUksRUFBRTt3QkFDSixTQUFTLEVBQUUsV0FBVyxDQUFDLEtBQUs7d0JBQzVCLDBCQUEwQixFQUFFLHdCQUF3Qjt3QkFDcEQsbUJBQW1CLEVBQUUsZ0JBQWdCLElBQUksR0FBRztxQkFDN0M7aUJBQ0Y7YUFDRjtTQUNGLENBQUM7UUFDRixhQUFhO1FBQ2IsSUFBSSxDQUFDLFFBQVEsR0FBRyxVQUFVLENBQUMsR0FBRztZQUM1QixNQUFNLEVBQUUsd0JBQXdCO1lBQ2hDLE9BQU8sRUFBRSxDQUFDLFNBQVMsR0FBRyxVQUFVLENBQUM7WUFDakMsU0FBUyxFQUFFLGVBQWU7WUFDMUIsYUFBYSxFQUFFO2dCQUNiLFNBQVMsRUFBRSxPQUFPO2dCQUNsQixVQUFVLEVBQUUsT0FBTztnQkFDbkIsVUFBVSxFQUFFLE9BQU87Z0JBQ25CLGVBQWUsRUFBRSxPQUFPO2FBQ3pCO1lBQ0QsVUFBVSxFQUFFO2dCQUNWLFFBQVEsRUFBRTtvQkFDUixPQUFPLEVBQUUsY0FBYztpQkFDeEI7Z0JBQ0QsV0FBVyxFQUFFLEtBQUs7YUFDbkI7WUFDRCxPQUFPLEVBQUU7Z0JBQ1AsZ0JBQWdCLEVBQUU7Z0JBQ2xCLDJCQUEyQjtnQkFDM0Isd0VBQXdFO2dCQUN4RTtvQkFDRSxJQUFJLEVBQUUsZ0NBQWdDO29CQUN0QyxJQUFJLEVBQUUsNkNBQTZDO29CQUNuRCxJQUFJLEVBQUU7d0JBQ0osVUFBVSxFQUFFLHdCQUF3Qjt3QkFDcEMseUJBQXlCLEVBQUUsdUNBQXVDO3dCQUNsRSwwQkFBMEIsRUFBRSx3Q0FBd0M7d0JBQ3BFLFNBQVMsRUFBRSx1QkFBdUI7d0JBQ2xDLGNBQWMsRUFBRSw2QkFBNkI7d0JBQzdDLGlCQUFpQixFQUFFLCtCQUErQjt3QkFDbEQsZUFBZSxFQUFFLDZCQUE2QjtxQkFDL0M7aUJBQ0Y7YUFDRjtTQUNGLENBQUM7SUFDSixDQUFDO0lBRUQsTUFBTSxlQUFlLEdBQUcsSUFBSSxjQUFjLENBQUM7UUFDekMsSUFBSSxFQUFFLDRCQUE0QixDQUFDLGdCQUFnQixJQUFJLFVBQVUsQ0FBQyxFQUFFLENBQUMsQ0FBQyxDQUFDLENBQUMsS0FBSyxHQUFFLHFCQUFxQixDQUFDLFVBQVUsQ0FBQyxFQUFHLENBQUMsQ0FBQyxDQUFDLENBQUMsRUFBRyxFQUFFO1FBQzVILEVBQUUsRUFBRSxzQkFBc0IsQ0FBQyxVQUFVLENBQUMsRUFBRSxDQUFDO1FBQ3pDLElBQUksRUFBRTtZQUNKLEdBQUcsSUFBSTtZQUNQLFVBQVUsRUFBRTtnQkFDVixNQUFNLEVBQUUsWUFBWTtnQkFDcEIsU0FBUyxFQUFFLGVBQWU7Z0JBQzFCLGFBQWEsRUFBRTtvQkFDYixTQUFTLEVBQUUsT0FBTztvQkFDbEIsVUFBVSxFQUFFLE9BQU87b0JBQ25CLFVBQVUsRUFBRSxPQUFPO29CQUNuQixlQUFlLEVBQUUsT0FBTztpQkFDekI7Z0JBQ0QsT0FBTyxFQUFFLE1BQU0sQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLENBQUMsTUFBTSxDQUFDLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxDQUFDLFVBQVUsQ0FBQyxRQUFRLENBQUMsQ0FBQztnQkFDOUQsT0FBTyxFQUFFO29CQUNQLGdCQUFnQixFQUFFO29CQUNsQjt3QkFDRSxJQUFJLEVBQUUsdUJBQXVCO3dCQUM3QixJQUFJLEVBQUUsNkNBQTZDLEdBQUMsd0NBQXdDO3dCQUM1RixJQUFJLEVBQUU7NEJBQ0osTUFBTSxFQUFFLE9BQU87NEJBQ2YsY0FBYyxFQUFFLDZCQUE2Qjs0QkFDN0Msa0JBQWtCLEVBQUUsSUFBSSxDQUFDLFNBQVMsQ0FBQyxvQkFBb0IsQ0FBQzt5QkFDekQ7cUJBQ0Y7aUJBQ0Y7YUFDRjtTQUNGO0tBQ0YsQ0FBQyxDQUFDO0lBRUgsT0FBTztRQUNMLFFBQVEsRUFBRSxzQ0FBc0MsQ0FBQyxnQkFBZ0IsSUFBSSxVQUFVLENBQUMsRUFBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLEdBQUcsR0FBQyxVQUFVLENBQUMsRUFBRyxDQUFDLENBQUMsQ0FBQyxFQUFHLE1BQU07UUFDcEgsT0FBTyxFQUFFLGVBQWU7S0FDekIsQ0FBQztBQUNKLENBQUM7QUFFRCxTQUFTLGNBQWMsQ0FBQyxZQUFrQyxFQUFFLEtBQXFCLEVBQy9FLGdCQUF5QixFQUFFLFlBQW1DO0lBRTlELFNBQVMsZUFBZSxDQUFDLElBQWtCLEVBQUUsVUFBa0I7UUFDN0QsT0FBTyxXQUFXLFVBQVUsS0FBSyxJQUFJLENBQUMsRUFBRSxFQUFFLENBQUM7SUFDN0MsQ0FBQztJQUNELFNBQVMsZ0JBQWdCLENBQUMsS0FBb0IsRUFBRSxVQUFrQjtRQUNoRSxPQUFPLFdBQVcsVUFBVSxNQUFNLEtBQUssQ0FBQyxJQUFJLENBQUMsRUFBRSxHQUFHLEtBQUssQ0FBQyxJQUFJLENBQUMsU0FBUyxHQUFHLEtBQUssQ0FBQyxFQUFFLEVBQUUsQ0FBQztJQUN0RixDQUFDO0lBQ0QsU0FBUyxnQkFBZ0IsQ0FBQyxLQUFvQixFQUFFLFVBQWtCO1FBQ2hFLE9BQU8sV0FBVyxVQUFVLE1BQU0sS0FBSyxDQUFDLEVBQUUsRUFBRSxDQUFDO0lBQy9DLENBQUM7SUFFRCxNQUFNLElBQUksR0FBRyxFQUFFLENBQUM7SUFDaEIsS0FBSyxJQUFJLENBQUMsVUFBVSxFQUFFLGFBQWEsQ0FBQyxJQUFJLE1BQU0sQ0FBQyxPQUFPLENBQUMsWUFBWSxDQUFDLFFBQVEsQ0FBQyxFQUFFLENBQUM7UUFDOUUsTUFBTSxxQkFBcUIsR0FBRyxlQUFlLENBQUMsYUFBYSxDQUFDLEtBQUssRUFBRSxVQUFVLENBQUMsSUFBSSxTQUFTLENBQUM7UUFDNUYsTUFBTSxnQkFBZ0IsR0FBRyxlQUFlLENBQUMsYUFBYSxDQUFDLE1BQU0sRUFBRSxPQUFPLENBQUMsSUFBSSxTQUFTLENBQUM7UUFDckYsSUFBSSxxQkFBcUIsS0FBSyxnQkFBZ0IsRUFBRSxDQUFDO1lBQy9DLE1BQU0sSUFBSSxLQUFLLENBQUMsa0ZBQWtGLENBQUMsQ0FBQztRQUN0RyxDQUFDO1FBQ0QsSUFBSSxDQUFDLGFBQWEsQ0FBQyxNQUFNLENBQUMsUUFBUSxDQUFDLGlCQUFpQixDQUFDLEVBQUUsQ0FBQztZQUN0RCxNQUFNLElBQUksS0FBSyxDQUFDLG1GQUFtRixhQUFhLENBQUMsTUFBTSxFQUFFLENBQUMsQ0FBQztRQUM3SCxDQUFDO1FBRUQsb0NBQW9DO1FBQ3BDLE1BQU0sZ0JBQWdCLEdBQUcsWUFBWSxDQUFDLGdCQUFnQixJQUFJLFlBQVksRUFBRSxnQkFBZ0IsQ0FBQztRQUN6RixNQUFNLHdCQUF3QixHQUFHLFdBQVcsQ0FBQyxnQkFBZ0IsRUFBRSxnQkFBZ0IsQ0FBQyxDQUFDO1FBRWpGLE1BQU0sVUFBVSxHQUFHLFNBQVMsR0FBRyxVQUFVLENBQUM7UUFDMUMsYUFBYTtRQUNiLElBQUksQ0FBQyxVQUFVLENBQUMsR0FBRztZQUNqQixNQUFNLEVBQUUsUUFBUSxHQUFHLFVBQVU7WUFDN0IsU0FBUyxFQUFFLGVBQWU7WUFDMUIsT0FBTyxFQUFFO2dCQUNQLGdCQUFnQixFQUFFO2dCQUNsQjtvQkFDRSxJQUFJLEVBQUUsZ0NBQWdDO29CQUN0QyxJQUFJLEVBQUUsOENBQThDO29CQUNwRCxJQUFJLEVBQUU7d0JBQ0osU0FBUyxFQUFFLGFBQWEsQ0FBQyxLQUFLO3dCQUM5QiwwQkFBMEIsRUFBRSx3QkFBd0I7d0JBQ3BELG1CQUFtQixFQUFFLGdCQUFnQixJQUFJLEdBQUc7cUJBQzdDO2lCQUNGO2FBQ0Y7U0FDRixDQUFDO1FBRUYsZ0VBQWdFO1FBQ2hFLElBQUksWUFBWSxDQUFDLGFBQWEsS0FBSyxNQUFNLEVBQUUsQ0FBQztZQUMxQyxLQUFLLElBQUksQ0FBQyxHQUFHLENBQUMsRUFBRSxDQUFDLEdBQUcsS0FBSyxDQUFDLE1BQU0sRUFBRSxDQUFDLEVBQUUsRUFBRSxDQUFDO2dCQUN0QyxNQUFNLElBQUksR0FBRyxLQUFLLENBQUMsQ0FBQyxDQUFDLENBQUM7Z0JBQ3RCLE1BQU0sU0FBUyxHQUFHLGVBQWUsQ0FBQyxJQUFJLEVBQUUsVUFBVSxDQUFDLENBQUM7Z0JBRXBELE1BQU0sS0FBSyxHQUFhLEVBQUUsQ0FBQztnQkFDM0IsSUFBSSxDQUFDLElBQUksQ0FBQyxFQUFFLENBQUM7b0JBQ1gsS0FBSyxDQUFDLElBQUksQ0FBQyxVQUFVLENBQUMsQ0FBQztnQkFDekIsQ0FBQztxQkFBTSxJQUFJLENBQUMsR0FBRyxDQUFDLEVBQUUsQ0FBQztvQkFDakIsTUFBTSxpQkFBaUIsR0FBRyxlQUFlLENBQUMsS0FBSyxDQUFDLENBQUMsR0FBRyxDQUFDLENBQUMsRUFBRSxVQUFVLENBQUMsQ0FBQztvQkFDcEUsS0FBSyxDQUFDLElBQUksQ0FBQyxpQkFBaUIsQ0FBQyxDQUFDO2dCQUNoQyxDQUFDO2dCQUVELGFBQWE7Z0JBQ2IsSUFBSSxDQUFDLFNBQVMsQ0FBQyxHQUFHO29CQUNoQixNQUFNLEVBQUUsSUFBSSxVQUFVLFFBQVEsSUFBSSxDQUFDLEVBQUUsRUFBRTtvQkFDdkMsT0FBTyxFQUFFLEtBQUs7b0JBQ2QsU0FBUyxFQUFFLGVBQWU7b0JBQzFCLGFBQWEsRUFBRTt3QkFDYixTQUFTLEVBQUUsT0FBTzt3QkFDbEIsVUFBVSxFQUFFLE9BQU87d0JBQ25CLFVBQVUsRUFBRSxPQUFPO3FCQUNwQjtvQkFDRCxPQUFPLEVBQUU7d0JBQ1AsZ0JBQWdCLEVBQUU7d0JBQ2xCOzRCQUNFLElBQUksRUFBRSxpQ0FBaUM7NEJBQ3ZDLElBQUksRUFBRSwrQ0FBK0M7NEJBQ3JELElBQUksRUFBRTtnQ0FDSix5QkFBeUIsRUFBRSxHQUFHLElBQUksQ0FBQyxFQUFFLEdBQUcsSUFBSSxDQUFDLFNBQVMsR0FBRztnQ0FDekQsMEJBQTBCLEVBQUUsd0JBQXdCO2dDQUNwRCxTQUFTLEVBQUUsYUFBYSxDQUFDLE1BQU0sQ0FBQyxPQUFPLENBQUMsaUJBQWlCLEVBQUUsR0FBRyxJQUFJLENBQUMsRUFBRSxHQUFHLElBQUksQ0FBQyxTQUFTLEdBQUcsQ0FBQztnQ0FDMUYsaUJBQWlCLEVBQUUsWUFBWSxDQUFDLGFBQWE7Z0NBQzdDLGVBQWUsRUFBRSxZQUFZLENBQUMsWUFBWTtnQ0FDMUMsbUJBQW1CLEVBQUUsZ0JBQWdCLElBQUksR0FBRzs2QkFDN0M7eUJBQ0Y7cUJBQ0Y7aUJBQ0YsQ0FBQztZQUNKLENBQUM7UUFDSCxDQUFDO2FBQU0sSUFBSSxZQUFZLENBQUMsYUFBYSxLQUFLLE9BQU8sRUFBRSxDQUFDO1lBRWxELEtBQUssSUFBSSxDQUFDLEdBQUcsQ0FBQyxFQUFFLENBQUMsR0FBRyxLQUFLLENBQUMsTUFBTSxFQUFFLENBQUMsRUFBRSxFQUFFLENBQUM7Z0JBQ3RDLE1BQU0sSUFBSSxHQUFHLEtBQUssQ0FBQyxDQUFDLENBQUMsQ0FBQztnQkFFdEIsS0FBSyxJQUFJLENBQUMsR0FBRyxDQUFDLEVBQUUsQ0FBQyxHQUFHLElBQUksQ0FBQyxNQUFNLENBQUMsTUFBTSxFQUFFLENBQUMsRUFBRSxFQUFFLENBQUM7b0JBQzVDLE1BQU0sS0FBSyxHQUFHLElBQUksQ0FBQyxNQUFNLENBQUMsQ0FBQyxDQUFDLENBQUM7b0JBRTdCLE1BQU0sVUFBVSxHQUFHLGdCQUFnQixDQUFDLEtBQUssRUFBRSxVQUFVLENBQUMsQ0FBQztvQkFFdkQsTUFBTSxLQUFLLEdBQWEsRUFBRSxDQUFDO29CQUMzQixJQUFJLENBQUMsSUFBSSxDQUFDLEVBQUUsQ0FBQzt3QkFDWCxLQUFLLENBQUMsSUFBSSxDQUFDLFVBQVUsQ0FBQyxDQUFDO29CQUN6QixDQUFDO3lCQUFNLElBQUksQ0FBQyxHQUFHLENBQUMsRUFBRSxDQUFDO3dCQUNqQixnRkFBZ0Y7d0JBQ2hGLEtBQUssTUFBTSxLQUFLLElBQUksS0FBSyxDQUFDLENBQUMsR0FBRyxDQUFDLENBQUMsQ0FBQyxNQUFNLEVBQUUsQ0FBQzs0QkFDeEMsS0FBSyxDQUFDLElBQUksQ0FBQyxnQkFBZ0IsQ0FBQyxLQUFLLEVBQUUsVUFBVSxDQUFDLENBQUMsQ0FBQzt3QkFDbEQsQ0FBQztvQkFDSCxDQUFDO29CQUVELElBQUksSUFBSSxDQUFDLGdCQUFnQixJQUFJLENBQUMsR0FBRyxDQUFDLEVBQUUsQ0FBQzt3QkFDbkMsNEVBQTRFO3dCQUM1RSxNQUFNLGtCQUFrQixHQUFHLGdCQUFnQixDQUFDLElBQUksQ0FBQyxNQUFNLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FBQyxFQUFFLFVBQVUsQ0FBQyxDQUFDO3dCQUM1RSxLQUFLLENBQUMsSUFBSSxDQUFDLGtCQUFrQixDQUFDLENBQUM7b0JBQ2pDLENBQUM7b0JBRUQsYUFBYTtvQkFDYixJQUFJLENBQUMsVUFBVSxDQUFDLEdBQUc7d0JBQ2pCLE1BQU0sRUFBRSxJQUFJLFVBQVUsUUFBUSxJQUFJLENBQUMsRUFBRSxHQUFHLElBQUksQ0FBQyxTQUFTLEdBQUcsS0FBSyxDQUFDLEVBQUUsRUFBRTt3QkFDbkUsT0FBTyxFQUFFLEtBQUs7d0JBQ2QsU0FBUyxFQUFFLGVBQWU7d0JBQzFCLGFBQWEsRUFBRTs0QkFDYixTQUFTLEVBQUUsT0FBTzs0QkFDbEIsVUFBVSxFQUFFLE9BQU87NEJBQ25CLFVBQVUsRUFBRSxPQUFPO3lCQUNwQjt3QkFDRCxPQUFPLEVBQUU7NEJBQ1AsZ0JBQWdCLEVBQUU7NEJBQ2xCO2dDQUNFLElBQUksRUFBRSxpQ0FBaUM7Z0NBQ3ZDLElBQUksRUFBRSwrQ0FBK0M7Z0NBQ3JELElBQUksRUFBRTtvQ0FDSix5QkFBeUIsRUFBRSxHQUFHLElBQUksQ0FBQyxFQUFFLEdBQUcsSUFBSSxDQUFDLFNBQVMsR0FBRyxLQUFLLENBQUMsRUFBRSxHQUFHLElBQUksQ0FBQyxTQUFTLEdBQUc7b0NBQ3JGLDBCQUEwQixFQUFFLHdCQUF3QjtvQ0FDcEQsU0FBUyxFQUFFLGFBQWEsQ0FBQyxNQUFNLENBQUMsT0FBTyxDQUFDLGlCQUFpQixFQUFFLEdBQUcsSUFBSSxDQUFDLEVBQUUsR0FBRyxJQUFJLENBQUMsU0FBUyxHQUFHLEtBQUssQ0FBQyxFQUFFLEdBQUcsSUFBSSxDQUFDLFNBQVMsR0FBRyxDQUFDO29DQUN0SCxpQkFBaUIsRUFBRSxZQUFZLENBQUMsYUFBYTtvQ0FDN0MsZUFBZSxFQUFFLFlBQVksQ0FBQyxZQUFZO29DQUMxQyxtQkFBbUIsRUFBRSxnQkFBZ0IsSUFBSSxHQUFHO2lDQUM3Qzs2QkFDRjt5QkFDRjtxQkFDRixDQUFDO2dCQUNKLENBQUM7WUFDSCxDQUFDO1FBRUgsQ0FBQzthQUFNLElBQUksWUFBWSxDQUFDLGFBQWEsS0FBSyxPQUFPLEVBQUUsQ0FBQztZQUVsRCxLQUFLLElBQUksQ0FBQyxHQUFHLENBQUMsRUFBRSxDQUFDLEdBQUcsS0FBSyxDQUFDLE1BQU0sRUFBRSxDQUFDLEVBQUUsRUFBRSxDQUFDO2dCQUN0QyxNQUFNLElBQUksR0FBRyxLQUFLLENBQUMsQ0FBQyxDQUFDLENBQUM7Z0JBRXRCLEtBQUssSUFBSSxDQUFDLEdBQUcsQ0FBQyxFQUFFLENBQUMsR0FBRyxJQUFJLENBQUMsTUFBTSxDQUFDLE1BQU0sRUFBRSxDQUFDLEVBQUUsRUFBRSxDQUFDO29CQUM1QyxNQUFNLEtBQUssR0FBRyxJQUFJLENBQUMsTUFBTSxDQUFDLENBQUMsQ0FBQyxDQUFDO29CQUU3QixLQUFLLElBQUksRUFBRSxHQUFHLENBQUMsRUFBRSxFQUFFLEdBQUcsS0FBSyxDQUFDLE1BQU0sQ0FBQyxNQUFNLEVBQUUsRUFBRSxFQUFFLEVBQUUsQ0FBQzt3QkFDaEQsTUFBTSxLQUFLLEdBQUcsS0FBSyxDQUFDLE1BQU0sQ0FBQyxFQUFFLENBQUMsQ0FBQzt3QkFFL0IsTUFBTSxVQUFVLEdBQUcsZ0JBQWdCLENBQUMsS0FBSyxFQUFFLFVBQVUsQ0FBQyxDQUFDO3dCQUV2RCxNQUFNLEtBQUssR0FBYSxFQUFFLENBQUM7d0JBQzNCLElBQUksQ0FBQyxJQUFJLENBQUMsRUFBRSxDQUFDOzRCQUNYLEtBQUssQ0FBQyxJQUFJLENBQUMsVUFBVSxDQUFDLENBQUM7d0JBQ3pCLENBQUM7NkJBQU0sSUFBSSxDQUFDLEdBQUcsQ0FBQyxFQUFFLENBQUM7NEJBQ2pCLGdGQUFnRjs0QkFDaEYsS0FBSyxNQUFNLEtBQUssSUFBSSxLQUFLLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FBQyxDQUFDLE1BQU0sRUFBRSxDQUFDO2dDQUN4QyxLQUFLLE1BQU0sTUFBTSxJQUFJLEtBQUssQ0FBQyxNQUFNLEVBQUUsQ0FBQztvQ0FDbEMsS0FBSyxDQUFDLElBQUksQ0FBQyxnQkFBZ0IsQ0FBQyxNQUFNLEVBQUUsVUFBVSxDQUFDLENBQUMsQ0FBQztnQ0FDbkQsQ0FBQzs0QkFDSCxDQUFDO3dCQUNILENBQUM7d0JBRUQsSUFBSSxJQUFJLENBQUMsZ0JBQWdCLElBQUksQ0FBQyxHQUFHLENBQUMsRUFBRSxDQUFDOzRCQUNuQyxxRkFBcUY7NEJBQ3JGLEtBQUssTUFBTSxNQUFNLElBQUksSUFBSSxDQUFDLE1BQU0sQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUFDLENBQUMsTUFBTSxFQUFFLENBQUM7Z0NBQy9DLEtBQUssQ0FBQyxJQUFJLENBQUMsZ0JBQWdCLENBQUMsTUFBTSxFQUFFLFVBQVUsQ0FBQyxDQUFDLENBQUM7NEJBQ25ELENBQUM7d0JBQ0gsQ0FBQzt3QkFFRCxhQUFhO3dCQUNiLElBQUksQ0FBQyxVQUFVLENBQUMsR0FBRzs0QkFDakIsTUFBTSxFQUFFLElBQUksVUFBVSxRQUFRLEtBQUssQ0FBQyxFQUFFLEVBQUU7NEJBQ3hDLE9BQU8sRUFBRSxLQUFLOzRCQUNkLFNBQVMsRUFBRSxlQUFlOzRCQUMxQixhQUFhLEVBQUU7Z0NBQ2IsU0FBUyxFQUFFLE9BQU87Z0NBQ2xCLFVBQVUsRUFBRSxPQUFPO2dDQUNuQixVQUFVLEVBQUUsT0FBTzs2QkFDcEI7NEJBQ0QsT0FBTyxFQUFFO2dDQUNQLGdCQUFnQixFQUFFO2dDQUNsQjtvQ0FDRSxJQUFJLEVBQUUsaUNBQWlDO29DQUN2QyxJQUFJLEVBQUUsK0NBQStDO29DQUNyRCxJQUFJLEVBQUU7d0NBQ0oseUJBQXlCLEVBQUUsS0FBSyxDQUFDLEVBQUU7d0NBQ25DLDBCQUEwQixFQUFFLHdCQUF3Qjt3Q0FDcEQsU0FBUyxFQUFFLGFBQWEsQ0FBQyxNQUFNLENBQUMsT0FBTyxDQUFDLGlCQUFpQixFQUFFLEtBQUssQ0FBQyxFQUFFLENBQUM7d0NBQ3BFLGlCQUFpQixFQUFFLFlBQVksQ0FBQyxhQUFhO3dDQUM3QyxlQUFlLEVBQUUsWUFBWSxDQUFDLFlBQVk7d0NBQzFDLG1CQUFtQixFQUFFLGdCQUFnQixJQUFJLEdBQUc7cUNBQzdDO2lDQUNGOzZCQUNGO3lCQUNGLENBQUM7b0JBQ0osQ0FBQztnQkFDSCxDQUFDO1lBQ0gsQ0FBQztRQUVILENBQUM7SUFDSCxDQUFDO0lBRUQsTUFBTSxlQUFlLEdBQUcsSUFBSSxjQUFjLENBQUM7UUFDekMsSUFBSSxFQUFFLDhCQUE4QixDQUFDLGdCQUFnQixJQUFJLFlBQVksQ0FBQyxFQUFFLENBQUMsQ0FBQyxDQUFDLENBQUMsS0FBSyxHQUFFLHFCQUFxQixDQUFDLFlBQVksQ0FBQyxFQUFHLENBQUMsQ0FBQyxDQUFDLENBQUMsRUFBRyxFQUFFO1FBQ2xJLFdBQVcsRUFBRTtZQUNYLE9BQU8sRUFBRSw4QkFBOEIsQ0FBQyxnQkFBZ0IsSUFBSSxZQUFZLENBQUMsRUFBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLEdBQUcsR0FBQyxZQUFZLENBQUMsRUFBRyxDQUFDLENBQUMsQ0FBQyxFQUFHLEVBQUU7WUFDM0csb0JBQW9CLEVBQUUsS0FBSztTQUM1QjtRQUNELEVBQUUsRUFBRSxzQkFBc0IsQ0FBQyxZQUFZLENBQUMsRUFBRSxDQUFDO1FBQzNDLElBQUksRUFBRTtZQUNKLEdBQUcsSUFBSTtTQUNSO0tBQ0YsQ0FBQyxDQUFDO0lBRUgsT0FBTztRQUNMLFFBQVEsRUFBRSx3Q0FBd0MsQ0FBQyxnQkFBZ0IsSUFBSSxZQUFZLENBQUMsRUFBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLEdBQUcsR0FBQyxZQUFZLENBQUMsRUFBRyxDQUFDLENBQUMsQ0FBQyxFQUFHLE1BQU07UUFDMUgsT0FBTyxFQUFFLGVBQWU7S0FDekIsQ0FBQztBQUNKLENBQUMiLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgKiBhcyBmcyBmcm9tICdmcyc7XG5pbXBvcnQgKiBhcyBwYXRoIGZyb20gJ3BhdGgnO1xuaW1wb3J0IHsgc3RyaW5naWZ5IH0gZnJvbSAneWFtbCc7XG5pbXBvcnQgeyBJRXhwcmVzc1N0YWNrIH0gZnJvbSAnLi9leHByZXNzLXN0YWNrJztcbmltcG9ydCB7IElFeHByZXNzU3RhZ2UgfSBmcm9tICcuL2V4cHJlc3Mtc3RhZ2UnO1xuaW1wb3J0IHsgSUV4cHJlc3NXYXZlIH0gZnJvbSAnLi9leHByZXNzLXdhdmUnO1xuaW1wb3J0IHsgSnNvblBhdGNoLCBQYXRjaCB9IGZyb20gJy4vdXRpbHMvanNvbi1wYXRjaCc7XG5cbmV4cG9ydCBpbnRlcmZhY2UgR2l0SHViV29ya2Zsb3dDb25maWcge1xuICAvKipcbiAgICogQ29uZmlndXJhdGlvbiBmb3IgdGhlIGJ1aWxkIHN0ZXBzXG4gICAqL1xuICByZWFkb25seSBidWlsZENvbmZpZzogQnVpbGRXb3JrZmxvd0NvbmZpZztcblxuICAvKipcbiAgICogQ29uZmlndXJhdGlvbiBmb3IgdGhlIGRpZmYgd29ya2Zsb3dcbiAgICovXG4gIHJlYWRvbmx5IGRpZmY6IERpZmZXb3JrZmxvd0NvbmZpZ1tdO1xuXG4gIC8qKlxuICAgKiBDb25maWd1cmF0aW9uIGZvciB0aGUgZGVwbG95IHdvcmtmbG93XG4gICAqL1xuICByZWFkb25seSBkZXBsb3k6IERlcGxveVdvcmtmbG93Q29uZmlnW107XG5cbiAgLyoqXG4gICAqIFRoZSBkaXJlY3RvcnkgcGF0aCB3aGVyZSBHaXRIdWIgd29ya2Zsb3cgZmlsZXMgd2lsbCBiZSBzYXZlZC5cbiAgICogRGVmYXVsdHMgdG8gYC5naXRodWJgIGluIHRoZSBjdXJyZW50IHdvcmtpbmcgZGlyZWN0b3J5LlxuICAgKlxuICAgKiBAZGVmYXVsdCBwYXRoLmpvaW4ocHJvY2Vzcy5jd2QoKSwgJy5naXRodWInKVxuICAgKi9cbiAgcmVhZG9ubHkgZGlyZWN0b3J5Pzogc3RyaW5nO1xuXG4gIC8qKlxuICAgKiBUaGUgc3ViZGlyZWN0b3J5IHdoZXJlIENESyBjb21tYW5kcyBzaG91bGQgcnVuLiBEZWZhdWx0cyB0byB0aGUgcmVwb3NpdG9yeSByb290LlxuICAgKiBQYXRocyBpbiBjb21tYW5kcyAoLS1vdXRwdXQsIC0tYXBwKSB3aWxsIGJlIHJlc29sdmVkIHJlbGF0aXZlIHRvIHRoaXMgZGlyZWN0b3J5LlxuICAgKiBAZGVmYXVsdCB1bmRlZmluZWQgKGNvbW1hbmRzIHJ1biBmcm9tIHJlcG8gcm9vdClcbiAgICovXG4gIHJlYWRvbmx5IHdvcmtpbmdEaXJlY3Rvcnk/OiBzdHJpbmc7XG59XG5cbmV4cG9ydCBpbnRlcmZhY2UgQnVpbGRXb3JrZmxvd0NvbmZpZyB7XG4gIC8qKlxuICAgKiBUaGUgdHlwZSBvZiB3b3JrZmxvdyB0byB1c2VcbiAgICovXG4gIHJlYWRvbmx5IHR5cGU6ICdwcmVzZXQtbnBtJyB8ICdwcmVzZXQtcG5wbScgfCAnd29ya2Zsb3cnO1xuXG4gIC8qKlxuICAgKiBPbmx5IHJlcXVpcmVkIGlmIHR5cGUgaXMgJ3dvcmtmbG93Jy4gU3BlY2lmeSB0aGUgd29ya2Zsb3cgb3IgcmV1c2FibGUgYWN0aW9uIHRvIHVzZSBmb3IgYnVpbGRpbmdcbiAgICovXG4gIHJlYWRvbmx5IHdvcmtmbG93PzogV29ya2Zsb3dMb2NhdGlvbjtcbn1cblxuZXhwb3J0IGludGVyZmFjZSBXb3JrZmxvd0xvY2F0aW9uIHtcbiAgLyoqXG4gICAqIFRoZSBwYXRoIG9mIHRoZSB3b3JrZmxvdyB0byBjYWxsIGJlZm9yZSBzeW50aGVzaXNcbiAgICovXG4gIHJlYWRvbmx5IHBhdGg6IHN0cmluZztcbn1cblxuZXhwb3J0IGludGVyZmFjZSBXb3JrZmxvd1RyaWdnZXJzUHVsbFJlcXVlc3RzIHtcbiAgcmVhZG9ubHkgYnJhbmNoZXM/OiBzdHJpbmdbXTtcbn1cbmV4cG9ydCBpbnRlcmZhY2UgV29ya2Zsb3dUcmlnZ2Vyc1B1c2gge1xuICByZWFkb25seSBicmFuY2hlcz86IHN0cmluZ1tdO1xufVxuZXhwb3J0IGludGVyZmFjZSBXb3JrZmxvd1RyaWdnZXJzIHtcbiAgcmVhZG9ubHkgcHVsbFJlcXVlc3Q/OiBXb3JrZmxvd1RyaWdnZXJzUHVsbFJlcXVlc3RzO1xuICByZWFkb25seSBwdXNoPzogV29ya2Zsb3dUcmlnZ2Vyc1B1c2g7XG59XG5cbmV4cG9ydCBpbnRlcmZhY2UgRGlmZkNvbW1hbmQge1xuICByZWFkb25seSBzeW50aDogc3RyaW5nO1xuICByZWFkb25seSBkaWZmOiBzdHJpbmc7XG59XG5leHBvcnQgaW50ZXJmYWNlIERlcGxveUNvbW1hbmQge1xuICByZWFkb25seSBzeW50aDogc3RyaW5nO1xuICByZWFkb25seSBkZXBsb3k6IHN0cmluZztcbn1cbmV4cG9ydCBpbnRlcmZhY2UgRGlmZldvcmtmbG93Q29uZmlnIHtcbiAgLyoqXG4gICAqIFVuaXF1ZSBpZGVudGlmaWVyLCBwb3N0Zml4ZWQgdG8gdGhlIGdlbmVyYXRlZCB3b3JrZmxvdyBuYW1lLiBDYW4gYmUgb21pdHRlZCBpZiBvbmx5IG9uZSB3b3JrZmxvdyBpcyBzcGVjaWZpZWQuXG4gICAqL1xuICByZWFkb25seSBpZD86IHN0cmluZztcblxuICAvKipcbiAgKiBDb25kaXRpb25zIHRoYXQgdHJpZ2dlciB0aGUgZGlmZiB3b3JrZmxvd1xuICAqICovXG4gIHJlYWRvbmx5IG9uOiBXb3JrZmxvd1RyaWdnZXJzO1xuXG4gIC8qKlxuICAgKiBBUk4gb2YgdGhlIHJvbGUgdG8gYXNzdW1lIGZvciB0aGUgZGlmZiBvcGVyYXRpb25cbiAgICovXG4gIHJlYWRvbmx5IGFzc3VtZVJvbGVBcm46IHN0cmluZztcblxuICAvKipcbiAgICogQVdTIHJlZ2lvbiB0byBhc3N1bWUgZm9yIHRoZSBkaWZmIG9wZXJhdGlvblxuICAgKi9cbiAgcmVhZG9ubHkgYXNzdW1lUmVnaW9uOiBzdHJpbmc7XG5cbiAgLyoqXG4gICAqIFNlbGVjdG9yIGZvciB0aGUgc3RhY2sgdHlwZVxuICAgKi9cbiAgcmVhZG9ubHkgc3RhY2tTZWxlY3RvcjogJ3dhdmUnIHwgJ3N0YWdlJyB8ICdzdGFjayc7XG5cbiAgLyoqXG4gICAqIENvbW1hbmRzIHRvIHJ1biBmb3IgZGlmZiwgdGhlIGtleSBpcyB1c2VkIHRvIGlkZW50aWZ5IHRoZSBjb21tYW5kcyBpbiBqb2IgbmFtZXNcbiAgICovXG4gIHJlYWRvbmx5IGNvbW1hbmRzOiBSZWNvcmQ8c3RyaW5nLCBEaWZmQ29tbWFuZD47XG5cbiAgLyoqXG4gICAqIFRoZSBzdWJkaXJlY3Rvcnkgd2hlcmUgQ0RLIGNvbW1hbmRzIHNob3VsZCBydW5cbiAgICogQGRlZmF1bHQgaW5oZXJpdGVkIGZyb20gR2l0SHViV29ya2Zsb3dDb25maWcud29ya2luZ0RpcmVjdG9yeVxuICAgKi9cbiAgcmVhZG9ubHkgd29ya2luZ0RpcmVjdG9yeT86IHN0cmluZztcbn1cblxuZXhwb3J0IGludGVyZmFjZSBEZXBsb3lXb3JrZmxvd0NvbmZpZyB7XG5cbiAgLyoqXG4gICAqIFVuaXF1ZSBpZGVudGlmaWVyLCBwb3N0Zml4ZWQgdG8gdGhlIGdlbmVyYXRlZCB3b3JrZmxvdyBuYW1lLiBDYW4gYmUgb21pdHRlZCBpZiBvbmx5IG9uZSB3b3JrZmxvdyBpcyBzcGVjaWZpZWQuXG4gICAqL1xuICByZWFkb25seSBpZD86IHN0cmluZztcblxuICAvKipcbiAgICogQ29uZGl0aW9ucyB0aGF0IHRyaWdnZXIgdGhlIGRlcGxveSB3b3JrZmxvd1xuICAgKi9cbiAgcmVhZG9ubHkgb246IFdvcmtmbG93VHJpZ2dlcnM7XG5cbiAgLyoqXG4gICAqIEFSTiBvZiB0aGUgcm9sZSB0byBhc3N1bWUgZm9yIHRoZSBkaWZmIG9wZXJhdGlvblxuICAgKi9cbiAgcmVhZG9ubHkgYXNzdW1lUm9sZUFybjogc3RyaW5nO1xuXG4gIC8qKlxuICAgKiBBV1MgcmVnaW9uIHRvIGFzc3VtZSBmb3IgdGhlIGRpZmYgb3BlcmF0aW9uXG4gICAqL1xuICByZWFkb25seSBhc3N1bWVSZWdpb246IHN0cmluZztcblxuICAvKipcbiAgICogU2VsZWN0b3IgZm9yIHRoZSBzdGFjayB0eXBlXG4gICAqL1xuICByZWFkb25seSBzdGFja1NlbGVjdG9yOiAnd2F2ZScgfCAnc3RhZ2UnIHwgJ3N0YWNrJztcblxuICAvKipcbiAgICogQ29tbWFuZHMgdG8gcnVuIGZvciBkZXBsb3ksIHRoZSBrZXkgaXMgdXNlZCB0byBpZGVudGlmeSB0aGUgY29tbWFuZHMgaW4gam9iIG5hbWVzXG4gICAqL1xuICByZWFkb25seSBjb21tYW5kczogUmVjb3JkPHN0cmluZywgRGVwbG95Q29tbWFuZD47XG5cbiAgLyoqXG4gICAqIFRoZSBzdWJkaXJlY3Rvcnkgd2hlcmUgQ0RLIGNvbW1hbmRzIHNob3VsZCBydW5cbiAgICogQGRlZmF1bHQgaW5oZXJpdGVkIGZyb20gR2l0SHViV29ya2Zsb3dDb25maWcud29ya2luZ0RpcmVjdG9yeVxuICAgKi9cbiAgcmVhZG9ubHkgd29ya2luZ0RpcmVjdG9yeT86IHN0cmluZztcbn1cblxuXG5leHBvcnQgY2xhc3MgR2l0aHViV29ya2Zsb3cge1xuXG4gIHB1YmxpYyBqc29uOiBvYmplY3Q7XG5cbiAgY29uc3RydWN0b3IoanNvbjogb2JqZWN0KSB7XG4gICAgdGhpcy5qc29uID0ganNvbjtcbiAgfVxuXG4gIC8qKlxuICAgKiBBcHBsaWVzIGEgc2V0IG9mIEpTT04tUGF0Y2ggKFJGQy02OTAyKSBvcGVyYXRpb25zIHRvIHRoaXMgb2JqZWN0IGFuZCByZXR1cm5zIHRoZSByZXN1bHQuXG4gICAqIEBwYXJhbSBvcHMgVGhlIG9wZXJhdGlvbnMgdG8gYXBwbHlcbiAgICogQHJldHVybnMgVGhlIHJlc3VsdCBvYmplY3RcbiAgICovXG4gIHB1YmxpYyBwYXRjaCguLi5vcHM6IFBhdGNoW10pOiBHaXRodWJXb3JrZmxvdyB7XG4gICAgY29uc3QganNvblBhdGNoID0gbmV3IEpzb25QYXRjaCgpO1xuICAgIGNvbnN0IHJlc3VsdCA9IGpzb25QYXRjaC5wYXRjaCh7IC4uLnRoaXMuanNvbiB9LCAuLi5vcHMpO1xuICAgIHRoaXMuanNvbiA9IHJlc3VsdDtcbiAgICByZXR1cm4gbmV3IEdpdGh1YldvcmtmbG93KHJlc3VsdCk7XG4gIH1cbn1cblxuZXhwb3J0IGludGVyZmFjZSBHaXRodWJXb3JrZmxvd0ZpbGUge1xuICByZWFkb25seSBmaWxlTmFtZTogc3RyaW5nO1xuICByZWFkb25seSBjb250ZW50OiBHaXRodWJXb3JrZmxvdztcbn1cblxuXG5jb25zdCBBVVRPX0dFTkVSQVRFRF9DT01NRU5UID0gJyMgfn4gR2VuZXJhdGVkIGJ5IGNkay1leHByZXNzLXBpcGVsaW5lLiBUbyBtb2RpZnksIGVkaXQgeW91ciBwaXBlbGluZSBhbmQgcnVuIGBjZGsgc3ludGhgJztcbmNvbnN0IENES19FWFBSRVNTX1BJUEVMSU5FX0dJVEhVQl9ESUZGX1ZFUlNJT04gPSAnMC4xLjUnO1xuXG5leHBvcnQgZnVuY3Rpb24gY3JlYXRlR2l0SHViV29ya2Zsb3dzKGdpdGh1YkNvbmZpZzogR2l0SHViV29ya2Zsb3dDb25maWcsIHdhdmVzOiBJRXhwcmVzc1dhdmVbXSkge1xuXG4gIGNvbnN0IHdvcmtmbG93RmlsZXM6IEdpdGh1YldvcmtmbG93RmlsZVtdID0gW107XG4gIHdvcmtmbG93RmlsZXMucHVzaChzeW50aFJldXNhYmxlQWN0aW9uKGdpdGh1YkNvbmZpZy5idWlsZENvbmZpZykpO1xuICB3b3JrZmxvd0ZpbGVzLnB1c2goZGlmZlJldXNhYmxlQWN0aW9uKCkpO1xuICB3b3JrZmxvd0ZpbGVzLnB1c2goZGVwbG95UmV1c2FibGVBY3Rpb24oZ2l0aHViQ29uZmlnLmJ1aWxkQ29uZmlnKSk7XG5cblxuICBmb3IgKGNvbnN0IGRpZmZDb25maWcgb2YgZ2l0aHViQ29uZmlnLmRpZmYpIHtcbiAgICBjb25zdCBoYXNNdWx0aXBsZVdvcmtmbG93cyA9IGdpdGh1YkNvbmZpZy5kaWZmLmxlbmd0aCA+IDE7XG4gICAgaWYgKCFkaWZmQ29uZmlnLmlkICYmIGhhc011bHRpcGxlV29ya2Zsb3dzKSB7XG4gICAgICB0aHJvdyBuZXcgRXJyb3IoJ0RpZmYgd29ya2Zsb3cgY29uZmlndXJhdGlvbiBtdXN0IGhhdmUgYW4gaWQnKTtcbiAgICB9XG5cbiAgICB3b3JrZmxvd0ZpbGVzLnB1c2goZGlmZldvcmtmbG93KGRpZmZDb25maWcsIHdhdmVzLCBoYXNNdWx0aXBsZVdvcmtmbG93cywgZ2l0aHViQ29uZmlnKSk7XG4gIH1cblxuICBmb3IgKGNvbnN0IGRlcGxveUNvbmZpZyBvZiBnaXRodWJDb25maWcuZGVwbG95KSB7XG4gICAgY29uc3QgaGFzTXVsdGlwbGVXb3JrZmxvd3MgPSBnaXRodWJDb25maWcuZGVwbG95Lmxlbmd0aCA+IDE7XG4gICAgaWYgKCFkZXBsb3lDb25maWcuaWQgJiYgaGFzTXVsdGlwbGVXb3JrZmxvd3MpIHtcbiAgICAgIHRocm93IG5ldyBFcnJvcignRGVwbG95IHdvcmtmbG93IGNvbmZpZ3VyYXRpb24gbXVzdCBoYXZlIGFuIGlkJyk7XG4gICAgfVxuXG4gICAgd29ya2Zsb3dGaWxlcy5wdXNoKGRlcGxveVdvcmtmbG93KGRlcGxveUNvbmZpZywgd2F2ZXMsIGhhc011bHRpcGxlV29ya2Zsb3dzLCBnaXRodWJDb25maWcpKTtcbiAgfVxuXG4gIHJldHVybiB3b3JrZmxvd0ZpbGVzO1xufVxuXG5leHBvcnQgZnVuY3Rpb24gc2F2ZVdvcmtmbG93VGVtcGxhdGVzKHRlbXBsYXRlczogR2l0aHViV29ya2Zsb3dGaWxlW10sIGRpcmVjdG9yeT86IHN0cmluZykge1xuICBjb25zdCBnaXRodWJEaXIgPSBkaXJlY3RvcnkgfHwgcGF0aC5qb2luKHByb2Nlc3MuY3dkKCksICcuZ2l0aHViJyk7XG4gIGlmICghZnMuZXhpc3RzU3luYyhnaXRodWJEaXIpKSB7XG4gICAgZnMubWtkaXJTeW5jKGdpdGh1YkRpciwgeyByZWN1cnNpdmU6IHRydWUgfSk7XG4gIH1cblxuICB0ZW1wbGF0ZXMuZm9yRWFjaCh0ZW1wbGF0ZSA9PiB7XG4gICAgY29uc3QgZmlsZVBhdGggPSBwYXRoLmpvaW4oZ2l0aHViRGlyLCB0ZW1wbGF0ZS5maWxlTmFtZSk7XG4gICAgY29uc3QgZGlyUGF0aCA9IHBhdGguZGlybmFtZShmaWxlUGF0aCk7XG4gICAgaWYgKCFmcy5leGlzdHNTeW5jKGRpclBhdGgpKSB7XG4gICAgICBmcy5ta2RpclN5bmMoZGlyUGF0aCwgeyByZWN1cnNpdmU6IHRydWUgfSk7XG4gICAgfVxuXG4gICAgY29uc3QgeWFtbENvbnRlbnQgPSBgJHtBVVRPX0dFTkVSQVRFRF9DT01NRU5UfVxcbiR7c3RyaW5naWZ5KHRlbXBsYXRlLmNvbnRlbnQuanNvbil9YDtcbiAgICBmcy53cml0ZUZpbGVTeW5jKGZpbGVQYXRoLCB5YW1sQ29udGVudCk7XG4gIH0pO1xufVxuXG4vKipcbiAqIFJlc29sdmVzIENESyBjbG91ZCBhc3NlbWJseSBwYXRoIHJlbGF0aXZlIHRvIHdvcmtpbmcgZGlyZWN0b3J5XG4gKi9cbmZ1bmN0aW9uIHJlc29sdmVQYXRoKGNsb3VkQXNzZW1ibHlQYXRoOiBzdHJpbmcsIHdvcmtpbmdEaXJlY3Rvcnk/OiBzdHJpbmcpOiBzdHJpbmcge1xuICBpZiAoIXdvcmtpbmdEaXJlY3RvcnkpIHJldHVybiBjbG91ZEFzc2VtYmx5UGF0aDtcbiAgLy8gT25seSBwcmVwZW5kIGlmIHBhdGggaXMgcmVsYXRpdmUgKG5vdCBhYnNvbHV0ZSlcbiAgaWYgKGNsb3VkQXNzZW1ibHlQYXRoLnN0YXJ0c1dpdGgoJy8nKSB8fCBjbG91ZEFzc2VtYmx5UGF0aC5zdGFydHNXaXRoKCcuJykpIHJldHVybiBjbG91ZEFzc2VtYmx5UGF0aDtcbiAgcmV0dXJuIGAke3dvcmtpbmdEaXJlY3Rvcnl9LyR7Y2xvdWRBc3NlbWJseVBhdGh9YDtcbn1cblxuZnVuY3Rpb24gc3ludGhSZXVzYWJsZUFjdGlvbihidWlsZENvbmZpZzogQnVpbGRXb3JrZmxvd0NvbmZpZyk6IEdpdGh1YldvcmtmbG93RmlsZSB7XG4gIGxldCBidWlsZFN0ZXBzOiBvYmplY3RbXSA9IFtdO1xuICBpZiAoYnVpbGRDb25maWcudHlwZSA9PT0gJ3ByZXNldC1ucG0nKSB7XG4gICAgYnVpbGRTdGVwcyA9IFt7XG4gICAgICBuYW1lOiAnU2V0IHVwIG5vZGUnLFxuICAgICAgdXNlczogJ2FjdGlvbnMvc2V0dXAtbm9kZUB2NCcsXG4gICAgICB3aXRoOiB7XG4gICAgICAgICdub2RlLXZlcnNpb24nOiAyMCxcbiAgICAgICAgJ2NhY2hlJzogJ25wbScsXG4gICAgICB9LFxuICAgIH0sXG4gICAge1xuICAgICAgbmFtZTogJ0luc3RhbGwgZGVwZW5kZW5jaWVzJyxcbiAgICAgIHJ1bjogJ25wbSBjaScsXG4gICAgICBzaGVsbDogJ2Jhc2gnLFxuICAgIH1dO1xuICB9IGVsc2UgaWYgKGJ1aWxkQ29uZmlnLnR5cGUgPT09ICdwcmVzZXQtcG5wbScpIHtcbiAgICBidWlsZFN0ZXBzID0gW1xuICAgICAgc2V0dXBQbnBtU3RlcCgpLFxuICAgICAge1xuICAgICAgICBuYW1lOiAnU2V0IHVwIG5vZGUnLFxuICAgICAgICB1c2VzOiAnYWN0aW9ucy9zZXR1cC1ub2RlQHY0JyxcbiAgICAgICAgd2l0aDoge1xuICAgICAgICAgICdub2RlLXZlcnNpb24nOiAyMCxcbiAgICAgICAgICAnY2FjaGUnOiAncG5wbScsXG4gICAgICAgIH0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBuYW1lOiAnSW5zdGFsbCBkZXBlbmRlbmNpZXMnLFxuICAgICAgICBydW46ICdwbnBtIGluc3RhbGwgLS1mcm96ZW4tbG9ja2ZpbGUnLFxuICAgICAgICBzaGVsbDogJ2Jhc2gnLFxuICAgICAgfSxcbiAgICBdO1xuICB9IGVsc2UgaWYgKGJ1aWxkQ29uZmlnLnR5cGUgPT09ICd3b3JrZmxvdycpIHtcbiAgICBpZiAoIWJ1aWxkQ29uZmlnLndvcmtmbG93Py5wYXRoKSB7XG4gICAgICB0aHJvdyBuZXcgRXJyb3IoJ1dvcmtmbG93IGlzIHJlcXVpcmVkIHdoZW4gdXNpbmcgXCJ3b3JrZmxvd1wiIHR5cGUgZm9yIGJ1aWxkJyk7XG4gICAgfVxuICAgIGJ1aWxkU3RlcHMgPSBbXG4gICAgICB7XG4gICAgICAgIG5hbWU6ICdCdWlsZCB3b3JrZmxvdycsXG4gICAgICAgIHVzZXM6IGJ1aWxkQ29uZmlnLndvcmtmbG93LnBhdGgsXG4gICAgICB9LFxuICAgIF07XG4gIH1cblxuICBjb25zdCB3b3JrZmxvd0NvbnRlbnQgPSBuZXcgR2l0aHViV29ya2Zsb3coe1xuICAgIG5hbWU6ICdDREsgRXhwcmVzcyBQaXBlbGluZSBTeW50aCBBY3Rpb24nLFxuICAgIGRlc2NyaXB0aW9uOiAnUnVuIENESyBzeW50aCBmb3IgYSBzcGVjaWZpYyBzdGFjayBwYXR0ZXJuIGFuZCBwb3N0IHJlc3VsdHMgdG8gUFInLFxuICAgIGlucHV0czoge1xuICAgICAgJ2NvbW1hbmQnOiB7XG4gICAgICAgIHJlcXVpcmVkOiB0cnVlLFxuICAgICAgICBkZXNjcmlwdGlvbjogJ0NESyBzeW50aCBjb21tYW5kJyxcbiAgICAgIH0sXG4gICAgICAnY2xvdWQtYXNzZW1ibHktZGlyZWN0b3J5Jzoge1xuICAgICAgICByZXF1aXJlZDogdHJ1ZSxcbiAgICAgICAgZGVzY3JpcHRpb246ICdUaGUgZGlyZWN0b3J5IHdoZXJlIHRoZSBDREsgY2xvdWQgYXNzZW1ibHkgc2hvdWxkIGJlIHN5bnRoZXNpemVkIHRvLCBtdXN0IGJlIHRoZSBzYW1lIGFzIHNwZWNpZmllZCBpbiB0aGUgY29tbWFuZCcsXG4gICAgICB9LFxuICAgICAgJ3dvcmtpbmctZGlyZWN0b3J5Jzoge1xuICAgICAgICByZXF1aXJlZDogZmFsc2UsXG4gICAgICAgIGRlc2NyaXB0aW9uOiAnVGhlIHN1YmRpcmVjdG9yeSB3aGVyZSBDREsgY29tbWFuZHMgc2hvdWxkIHJ1bicsXG4gICAgICAgIGRlZmF1bHQ6ICcuJyxcbiAgICAgIH0sXG4gICAgfSxcbiAgICBydW5zOiB7XG4gICAgICB1c2luZzogJ2NvbXBvc2l0ZScsXG4gICAgICBzdGVwczogW1xuICAgICAgICB7XG4gICAgICAgICAgbmFtZTogJ0NoZWNrb3V0IHJlcG8nLFxuICAgICAgICAgIHVzZXM6ICdhY3Rpb25zL2NoZWNrb3V0QHY0JyxcbiAgICAgICAgfSxcbiAgICAgICAgLi4uYnVpbGRTdGVwcyxcbiAgICAgICAge1xuICAgICAgICAgICduYW1lJzogJ0NESyBTeW50aCcsXG4gICAgICAgICAgJ3NoZWxsJzogJ2Jhc2gnLFxuICAgICAgICAgICd3b3JraW5nLWRpcmVjdG9yeSc6ICcke3sgaW5wdXRzLndvcmtpbmctZGlyZWN0b3J5IH19JyxcbiAgICAgICAgICAncnVuJzogJyR7eyBpbnB1dHMuY29tbWFuZCB9fScsXG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBuYW1lOiAnQ2FjaGUgQnVpbGQnLFxuICAgICAgICAgIHVzZXM6ICdhY3Rpb25zL2NhY2hlL3NhdmVAdjQnLFxuICAgICAgICAgIHdpdGg6IHtcbiAgICAgICAgICAgIGtleTogJ2NhY2hlLWJ1aWxkLSR7eyBnaXRodWIuc2hhIH19LSR7eyBpbnB1dHMuY2xvdWQtYXNzZW1ibHktZGlyZWN0b3J5IH19JyxcbiAgICAgICAgICAgIHBhdGg6IFtcbiAgICAgICAgICAgICAgJyR7eyBpbnB1dHMuY2xvdWQtYXNzZW1ibHktZGlyZWN0b3J5IH19LycsXG4gICAgICAgICAgICAgICdub2RlX21vZHVsZXMvJyxcbiAgICAgICAgICAgIF0uam9pbignXFxuJyksXG4gICAgICAgICAgfSxcbiAgICAgICAgfSxcbiAgICAgIF0sXG4gICAgfSxcbiAgfSk7XG5cbiAgcmV0dXJuIHtcbiAgICBmaWxlTmFtZTogJ2FjdGlvbnMvY2RrLWV4cHJlc3MtcGlwZWxpbmUtc3ludGgvYWN0aW9uLnltbCcsXG4gICAgY29udGVudDogd29ya2Zsb3dDb250ZW50LFxuICB9O1xufVxuZnVuY3Rpb24gZGlmZlJldXNhYmxlQWN0aW9uKCk6IEdpdGh1YldvcmtmbG93RmlsZSB7XG4gIGNvbnN0IHdvcmtmbG93Q29udGVudCA9IG5ldyBHaXRodWJXb3JrZmxvdyh7XG4gICAgbmFtZTogJ0NESyBEaWZmIEFjdGlvbicsXG4gICAgaW5wdXRzOiB7XG4gICAgICAnc3RhY2stc2VsZWN0b3ItcGF0dGVybnMnOiB7XG4gICAgICAgIHJlcXVpcmVkOiB0cnVlLFxuICAgICAgICBkZXNjcmlwdGlvbjogJ1RoZSB2YWx1ZSBvZiB0aGUge3N0YWNrU2VsZWN0b3J9IHJlcGxhY2VtZW50IGluIHRoZSBjb21tYW5kJyxcbiAgICAgIH0sXG4gICAgICAnY29tbWFuZCc6IHtcbiAgICAgICAgcmVxdWlyZWQ6IHRydWUsXG4gICAgICAgIGRlc2NyaXB0aW9uOiAnQ0RLIGRpZmYgY29tbWFuZCcsXG4gICAgICB9LFxuICAgICAgJ2Nsb3VkLWFzc2VtYmx5LWRpcmVjdG9yeSc6IHtcbiAgICAgICAgcmVxdWlyZWQ6IHRydWUsXG4gICAgICAgIGRlc2NyaXB0aW9uOiAnVGhlIGRpcmVjdG9yeSB3aGVyZSB0aGUgQ0RLIGNsb3VkIGFzc2VtYmx5IGlzIGxvY2F0ZWQnLFxuICAgICAgfSxcbiAgICAgICdnaXRodWItdG9rZW4nOiB7XG4gICAgICAgIHJlcXVpcmVkOiB0cnVlLFxuICAgICAgICBkZXNjcmlwdGlvbjogJ0dpdEh1YiB0b2tlbiBmb3IgcG9zdGluZyBjb21tZW50cycsXG4gICAgICB9LFxuICAgICAgJ2Fzc3VtZS1yb2xlLWFybic6IHtcbiAgICAgICAgcmVxdWlyZWQ6IHRydWUsXG4gICAgICAgIGRlc2NyaXB0aW9uOiAnVGhlIEFSTiBvZiB0aGUgcm9sZSB0byBhc3N1bWUgZm9yIHRoZSBkZXBsb3kgb3BlcmF0aW9uJyxcbiAgICAgIH0sXG4gICAgICAnYXNzdW1lLXJlZ2lvbic6IHtcbiAgICAgICAgcmVxdWlyZWQ6IHRydWUsXG4gICAgICAgIGRlc2NyaXB0aW9uOiAnVGhlIEFXUyByZWdpb24gdG8gYXNzdW1lIGZvciB0aGUgZGVwbG95IG9wZXJhdGlvbicsXG4gICAgICB9LFxuICAgICAgJ2pvYi1uYW1lJzoge1xuICAgICAgICByZXF1aXJlZDogZmFsc2UsXG4gICAgICAgIGRlc2NyaXB0aW9uOiAnTmFtZSBvZiB0aGUgam9iLCB1c2VkIHRvIGxpbmsgdG8gYWN0aW9uL2pvYiBsb2dzIGluIHN1bW1hcmllcycsXG4gICAgICB9LFxuICAgIH0sXG4gICAgcnVuczoge1xuICAgICAgdXNpbmc6ICdjb21wb3NpdGUnLFxuICAgICAgc3RlcHM6IFtcbiAgICAgICAgcmVzdG9yZUJ1aWxkQ2FjaGVTdGVwKCcke3sgaW5wdXRzLmNsb3VkLWFzc2VtYmx5LWRpcmVjdG9yeSB9fScpLFxuICAgICAgICBhc3N1bWVBd3NSb2xlU3RlcCgnJHt7IGlucHV0cy5hc3N1bWUtcm9sZS1hcm4gfX0nLCAnJHt7IGlucHV0cy5hc3N1bWUtcmVnaW9uIH19JyksXG4gICAgICAgIHtcbiAgICAgICAgICBuYW1lOiAnQ0RLIERpZmYgR2VuZXJhdGUnLFxuICAgICAgICAgIHVzZXM6ICdyZWhhbnZkbS9jZGstZXhwcmVzcy1waXBlbGluZS1naXRodWItZGlmZkB2JytDREtfRVhQUkVTU19QSVBFTElORV9HSVRIVUJfRElGRl9WRVJTSU9OLFxuICAgICAgICAgIHdpdGg6IHtcbiAgICAgICAgICAgICdtb2RlJzogJ2dlbmVyYXRlJyxcbiAgICAgICAgICAgICdjbG91ZC1hc3NlbWJseS1kaXJlY3RvcnknOiAnJHt7IGlucHV0cy5jbG91ZC1hc3NlbWJseS1kaXJlY3RvcnkgfX0nLFxuICAgICAgICAgICAgJ3N0YWNrLXNlbGVjdG9ycyc6ICcke3sgaW5wdXRzLnN0YWNrLXNlbGVjdG9yLXBhdHRlcm5zIH19JyxcbiAgICAgICAgICAgICdnaXRodWItdG9rZW4nOiAnJHt7IGlucHV0cy5naXRodWItdG9rZW4gfX0nLFxuICAgICAgICAgICAgJ2pvYi1uYW1lJzogJyR7eyBpbnB1dHMuam9iLW5hbWUgfX0nLFxuICAgICAgICAgIH0sXG4gICAgICAgIH0sXG4gICAgICBdLFxuICAgIH0sXG4gIH0pO1xuXG4gIHJldHVybiB7XG4gICAgZmlsZU5hbWU6ICdhY3Rpb25zL2Nkay1leHByZXNzLXBpcGVsaW5lLWRpZmYvYWN0aW9uLnltbCcsXG4gICAgY29udGVudDogd29ya2Zsb3dDb250ZW50LFxuICB9O1xufVxuZnVuY3Rpb24gZGVwbG95UmV1c2FibGVBY3Rpb24oYnVpbGRDb25maWc6IEJ1aWxkV29ya2Zsb3dDb25maWcpOiBHaXRodWJXb3JrZmxvd0ZpbGUge1xuICBjb25zdCB3b3JrZmxvd0NvbnRlbnQgPSBuZXcgR2l0aHViV29ya2Zsb3coe1xuICAgIG5hbWU6ICdDREsgRGVwbG95IEFjdGlvbicsXG4gICAgZGVzY3JpcHRpb246ICdSdW4gQ0RLIGRlcGxveSBmb3IgYSBzcGVjaWZpYyBzdGFjayBwYXR0ZXJuJyxcbiAgICBpbnB1dHM6IHtcbiAgICAgICdzdGFjay1zZWxlY3Rvci1wYXR0ZXJucyc6IHtcbiAgICAgICAgcmVxdWlyZWQ6IHRydWUsXG4gICAgICAgIGRlc2NyaXB0aW9uOiAnVGhlIHZhbHVlIG9mIHRoZSB7c3RhY2tTZWxlY3Rvcn0gcmVwbGFjZW1lbnQgaW4gdGhlIGNvbW1hbmQnLFxuICAgICAgfSxcbiAgICAgICdjb21tYW5kJzoge1xuICAgICAgICByZXF1aXJlZDogdHJ1ZSxcbiAgICAgICAgZGVzY3JpcHRpb246ICdDREsgZGVwbG95IGNvbW1hbmQnLFxuICAgICAgfSxcbiAgICAgICdjbG91ZC1hc3NlbWJseS1kaXJlY3RvcnknOiB7XG4gICAgICAgIHJlcXVpcmVkOiB0cnVlLFxuICAgICAgICBkZXNjcmlwdGlvbjogJ1RoZSBkaXJlY3Rvcnkgd2hlcmUgdGhlIENESyBjbG91ZCBhc3NlbWJseSBpcyBsb2NhdGVkJyxcbiAgICAgIH0sXG4gICAgICAnYXNzdW1lLXJvbGUtYXJuJzoge1xuICAgICAgICByZXF1aXJlZDogdHJ1ZSxcbiAgICAgICAgZGVzY3JpcHRpb246ICdUaGUgQVJOIG9mIHRoZSByb2xlIHRvIGFzc3VtZSBmb3IgdGhlIGRlcGxveSBvcGVyYXRpb24nLFxuICAgICAgfSxcbiAgICAgICdhc3N1bWUtcmVnaW9uJzoge1xuICAgICAgICByZXF1aXJlZDogdHJ1ZSxcbiAgICAgICAgZGVzY3JpcHRpb246ICdUaGUgQVdTIHJlZ2lvbiB0byBhc3N1bWUgZm9yIHRoZSBkZXBsb3kgb3BlcmF0aW9uJyxcbiAgICAgIH0sXG4gICAgICAnd29ya2luZy1kaXJlY3RvcnknOiB7XG4gICAgICAgIHJlcXVpcmVkOiBmYWxzZSxcbiAgICAgICAgZGVzY3JpcHRpb246ICdUaGUgc3ViZGlyZWN0b3J5IHdoZXJlIENESyBjb21tYW5kcyBzaG91bGQgcnVuJyxcbiAgICAgICAgZGVmYXVsdDogJy4nLFxuICAgICAgfSxcbiAgICB9LFxuICAgIHJ1bnM6IHtcbiAgICAgIHVzaW5nOiAnY29tcG9zaXRlJyxcbiAgICAgIHN0ZXBzOiBbXG4gICAgICAgIHJlc3RvcmVCdWlsZENhY2hlU3RlcCgnJHt7IGlucHV0cy5jbG91ZC1hc3NlbWJseS1kaXJlY3RvcnkgfX0nKSxcbiAgICAgICAgLi4uKGJ1aWxkQ29uZmlnLnR5cGUgPT09ICdwcmVzZXQtcG5wbScgPyBbXG4gICAgICAgICAgc2V0dXBQbnBtU3RlcCgpLFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIG5hbWU6ICdJbnN0YWxsIGRlcGVuZGVuY2llcycsXG4gICAgICAgICAgICBydW46ICdwbnBtIGluc3RhbGwgLS1mcm96ZW4tbG9ja2ZpbGUnLFxuICAgICAgICAgICAgc2hlbGw6ICdiYXNoJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdIDogW10pLFxuICAgICAgICBhc3N1bWVBd3NSb2xlU3RlcCgnJHt7IGlucHV0cy5hc3N1bWUtcm9sZS1hcm4gfX0nLCAnJHt7IGlucHV0cy5hc3N1bWUtcmVnaW9uIH19JyksXG4gICAgICAgIHtcbiAgICAgICAgICAnbmFtZSc6ICdDREsgRGVwbG95IENvbW1hbmQnLFxuICAgICAgICAgICd3b3JraW5nLWRpcmVjdG9yeSc6ICcke3sgaW5wdXRzLndvcmtpbmctZGlyZWN0b3J5IH19JyxcbiAgICAgICAgICAncnVuJzogJyR7eyBpbnB1dHMuY29tbWFuZCB9fScsXG4gICAgICAgICAgJ3NoZWxsJzogJ2Jhc2gnLFxuICAgICAgICB9LFxuICAgICAgXSxcbiAgICB9LFxuICB9KTtcblxuICByZXR1cm4ge1xuICAgIGZpbGVOYW1lOiAnYWN0aW9ucy9jZGstZXhwcmVzcy1waXBlbGluZS1kZXBsb3kvYWN0aW9uLnltbCcsXG4gICAgY29udGVudDogd29ya2Zsb3dDb250ZW50LFxuICB9O1xufVxuXG5cbmZ1bmN0aW9uIGNoZWNrb3V0UmVwb1N0ZXAoKSB7XG4gIHJldHVybiB7XG4gICAgbmFtZTogJ0NoZWNrb3V0IHJlcG8nLFxuICAgIHVzZXM6ICdhY3Rpb25zL2NoZWNrb3V0QHY0JyxcbiAgfTtcbn1cbmZ1bmN0aW9uIHJlc3RvcmVCdWlsZENhY2hlU3RlcChjbG91ZEFzc2VtYmx5RGlyOiBzdHJpbmcpIHtcbiAgcmV0dXJuIHtcbiAgICBuYW1lOiAnUmVzdG9yZSBCdWlsZCBDYWNoZScsXG4gICAgdXNlczogJ2FjdGlvbnMvY2FjaGUvcmVzdG9yZUB2NCcsXG4gICAgd2l0aDoge1xuICAgICAga2V5OiBgY2FjaGUtYnVpbGQtJFxce3sgZ2l0aHViLnNoYSB9fS0ke2Nsb3VkQXNzZW1ibHlEaXJ9YCxcbiAgICAgIHBhdGg6IFtcbiAgICAgICAgYCR7Y2xvdWRBc3NlbWJseURpcn0vYCxcbiAgICAgICAgJ25vZGVfbW9kdWxlcy8nLFxuICAgICAgXS5qb2luKCdcXG4nKSxcbiAgICB9LFxuICB9O1xufVxuZnVuY3Rpb24gYXNzdW1lQXdzUm9sZVN0ZXAoYXNzdW1lUm9sZUFybjogc3RyaW5nLCBhc3N1bWVSZWdpb246IHN0cmluZykge1xuICByZXR1cm4ge1xuICAgIG5hbWU6ICdDb25maWd1cmUgQVdTIGNyZWRlbnRpYWxzJyxcbiAgICB1c2VzOiAnYXdzLWFjdGlvbnMvY29uZmlndXJlLWF3cy1jcmVkZW50aWFsc0B2NCcsXG4gICAgd2l0aDoge1xuICAgICAgJ3JvbGUtdG8tYXNzdW1lJzogYXNzdW1lUm9sZUFybixcbiAgICAgICdhd3MtcmVnaW9uJzogYXNzdW1lUmVnaW9uLFxuICAgIH0sXG4gIH07XG59XG5mdW5jdGlvbiBzZXR1cFBucG1TdGVwKCkge1xuICByZXR1cm4ge1xuICAgIG5hbWU6ICdTZXR1cCBwbnBtJyxcbiAgICB1c2VzOiAncG5wbS9hY3Rpb24tc2V0dXBAdjQnLFxuICB9O1xufVxuXG5mdW5jdGlvbiBjYXBpdGFsaXplRmlyc3RMZXR0ZXIoaW5wdXQ6IHN0cmluZyk6IHN0cmluZyB7XG4gIGlmICghaW5wdXQpIHJldHVybiAnJztcbiAgcmV0dXJuIGlucHV0LmNoYXJBdCgwKS50b1VwcGVyQ2FzZSgpICsgaW5wdXQuc2xpY2UoMSk7XG59XG5cblxuZnVuY3Rpb24gZXh0cmFjdEFyZ3VtZW50KGNvbW1hbmQ6IHN0cmluZywgYXJnTmFtZTogc3RyaW5nKTogc3RyaW5nIHwgdW5kZWZpbmVkIHtcbiAgY29uc3QgbWF0Y2ggPSBjb21tYW5kLm1hdGNoKG5ldyBSZWdFeHAoYCR7YXJnTmFtZX0oPzo9fFxcXFxzKSg/OlwiKFteXCJdKylcInwnKFteJ10rKSd8KFxcXFxTKykpYCkpO1xuICAvLyBSZXR1cm4gd2hpY2hldmVyIGNhcHR1cmluZyBncm91cCBtYXRjaGVkIChkb3VibGUgcXVvdGVzLCBzaW5nbGUgcXVvdGVzLCBvciB1bnF1b3RlZClcbiAgcmV0dXJuIG1hdGNoID8gKG1hdGNoWzFdIHx8IG1hdGNoWzJdIHx8IG1hdGNoWzNdKSA6IHVuZGVmaW5lZDtcbn1cblxuZnVuY3Rpb24gZm9ybWF0V29ya2Zsb3dUcmlnZ2Vycyh3b3JrZmxvd1RyaWdnZXJzOiBXb3JrZmxvd1RyaWdnZXJzKSB7XG4gIGxldCB0cmlnZ2VyczogYW55ID0gd29ya2Zsb3dUcmlnZ2VycztcbiAgaWYgKHdvcmtmbG93VHJpZ2dlcnMucHVsbFJlcXVlc3QpIHtcbiAgICAvLyBOZWVkIHRvIGNoYW5nZSBgcHVsbFJlcXVlc3RgIHRvIGBwdWxsX3JlcXVlc3RgIHRvIG1hdGNoIEdpdEh1YiBBY3Rpb25zIHN5bnRheFxuICAgIHRyaWdnZXJzID0ge1xuICAgICAgLi4ud29ya2Zsb3dUcmlnZ2VycyxcbiAgICAgIHB1bGxfcmVxdWVzdDogd29ya2Zsb3dUcmlnZ2Vycy5wdWxsUmVxdWVzdCxcbiAgICB9O1xuICAgIGRlbGV0ZSB0cmlnZ2Vycy5wdWxsUmVxdWVzdDtcbiAgfVxuICByZXR1cm4gdHJpZ2dlcnM7XG59XG5mdW5jdGlvbiBkaWZmV29ya2Zsb3coZGlmZkNvbmZpZzogRGlmZldvcmtmbG93Q29uZmlnLCB3YXZlczogSUV4cHJlc3NXYXZlW10sXG4gIHJlcXVpcmVzVW5pcXVlSWQ6IGJvb2xlYW4sIGdpdGh1YkNvbmZpZz86IEdpdEh1YldvcmtmbG93Q29uZmlnKTogR2l0aHViV29ya2Zsb3dGaWxlIHtcblxuICBmdW5jdGlvbiB0b1NuYWtlQ2FzZShzdHI6IHN0cmluZyk6IHN0cmluZyB7XG4gICAgcmV0dXJuIHN0clxuICAgICAgLnJlcGxhY2UoLyhbYS16XSkoW0EtWl0pL2csICckMV8kMicpIC8vIGhhbmRsZSBjYW1lbENhc2Ugb3IgUGFzY2FsQ2FzZVxuICAgICAgLnJlcGxhY2UoL1tcXHNcXC1dKy9nLCAnXycpIC8vIHJlcGxhY2Ugc3BhY2VzIGFuZCBoeXBoZW5zIHdpdGggdW5kZXJzY29yZXNcbiAgICAgIC5yZXBsYWNlKC8oW0EtWl0rKS9nLCAnXyQxJykgLy8gYWRkIHVuZGVyc2NvcmVzIGJlZm9yZSB1cHBlcmNhc2Ugc2VxdWVuY2VzXG4gICAgICAucmVwbGFjZSgvXl8rfF8rJC9nLCAnJykgLy8gdHJpbSBsZWFkaW5nL3RyYWlsaW5nIHVuZGVyc2NvcmVzXG4gICAgICAudG9Mb3dlckNhc2UoKTtcbiAgfVxuICBmdW5jdGlvbiBzdGVwU3RhY2tTZWxlY3RvcnMoc3RhY2tTZWxlY3RvcjogJ3dhdmUnIHwgJ3N0YWdlJyB8ICdzdGFjaycpIHtcbiAgICBjb25zdCByZXM6IHsgbmFtZTogc3RyaW5nOyBzZWxlY3Rvcjogc3RyaW5nIH1bXSA9IFtdO1xuICAgIGZvciAoY29uc3Qgd2F2ZSBvZiB3YXZlcykge1xuICAgICAgaWYgKHN0YWNrU2VsZWN0b3IgPT09ICd3YXZlJykge1xuICAgICAgICByZXMucHVzaCh7XG4gICAgICAgICAgbmFtZTogdG9TbmFrZUNhc2Uod2F2ZS5pZCksXG4gICAgICAgICAgc2VsZWN0b3I6IGAke3dhdmUuaWR9JHt3YXZlLnNlcGFyYXRvcn0qYCxcbiAgICAgICAgfSk7XG4gICAgICB9IGVsc2UgaWYgKHN0YWNrU2VsZWN0b3IgPT09ICdzdGFnZScpIHtcbiAgICAgICAgZm9yIChjb25zdCBzdGFnZSBvZiB3YXZlLnN0YWdlcykge1xuICAgICAgICAgIHJlcy5wdXNoKHtcbiAgICAgICAgICAgIG5hbWU6IHRvU25ha2VDYXNlKHdhdmUuaWQgKyAnX18nICsgc3RhZ2UuaWQpLFxuICAgICAgICAgICAgc2VsZWN0b3I6IGAke3dhdmUuaWR9JHt3YXZlLnNlcGFyYXRvcn0ke3N0YWdlLmlkfSR7d2F2ZS5zZXBhcmF0b3J9KmAsXG4gICAgICAgICAgfSk7XG4gICAgICAgIH1cbiAgICAgIH0gZWxzZSBpZiAoc3RhY2tTZWxlY3RvciA9PT0gJ3N0YWNrJykge1xuICAgICAgICBmb3IgKGNvbnN0IHN0YWdlIG9mIHdhdmUuc3RhZ2VzKSB7XG4gICAgICAgICAgZm9yIChjb25zdCBzdGFjayBvZiBzdGFnZS5zdGFja3MpIHtcbiAgICAgICAgICAgIHJlcy5wdXNoKHtcbiAgICAgICAgICAgICAgbmFtZTogdG9TbmFrZUNhc2Uod2F2ZS5pZCArICdfXycgKyBzdGFnZS5pZCArICdfXycgKyBzdGFjay5pZCksXG4gICAgICAgICAgICAgIHNlbGVjdG9yOiBzdGFjay5pZCxcbiAgICAgICAgICAgIH0pO1xuICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgICAgfVxuICAgIH1cbiAgICByZXR1cm4gcmVzO1xuICB9XG5cblxuICBjb25zdCBqb2JzID0ge307XG4gIGNvbnN0IHByaW50Q2xvdWRBc3NlbWJsaWVzOiB7XG4gICAgaGVhZGVyOiBzdHJpbmc7XG4gICAgZGlyZWN0b3J5OiBzdHJpbmc7XG4gIH1bXSA9IFtdO1xuICBmb3IgKGxldCBbY29tbWFuZEtleSwgY29tbWFuZERpZmZdIG9mIE9iamVjdC5lbnRyaWVzKGRpZmZDb25maWcuY29tbWFuZHMpKSB7XG4gICAgY29uc3QgY2xvdWRBc3NlbWJseURpclN5bnRoID0gZXh0cmFjdEFyZ3VtZW50KGNvbW1hbmREaWZmLnN5bnRoLCAnLS1vdXRwdXQnKSB8fCAnY2RrLm91dCc7XG4gICAgY29uc3QgY2xvdWRBc3NlbWJseURpciA9IGV4dHJhY3RBcmd1bWVudChjb21tYW5kRGlmZi5kaWZmLCAnLS1hcHAnKSB8fCAnY2RrLm91dCc7XG4gICAgaWYgKGNsb3VkQXNzZW1ibHlEaXJTeW50aCAhPT0gY2xvdWRBc3NlbWJseURpcikge1xuICAgICAgdGhyb3cgbmV3IEVycm9yKCdUaGUgLS1vdXRwdXQgYXJndW1lbnQgb2Ygc3ludGggbXVzdCBiZSB0aGUgc2FtZSBhcyB0aGUgLS1hcHAgYXJndW1lbnQgZm9yIGRpZmYnKTtcbiAgICB9XG5cbiAgICAvLyBHZXQgYW5kIHJlc29sdmUgd29ya2luZyBkaXJlY3RvcnlcbiAgICBjb25zdCB3b3JraW5nRGlyZWN0b3J5ID0gZGlmZkNvbmZpZy53b3JraW5nRGlyZWN0b3J5IHx8IGdpdGh1YkNvbmZpZz8ud29ya2luZ0RpcmVjdG9yeTtcbiAgICBjb25zdCByZXNvbHZlZENsb3VkQXNzZW1ibHlEaXIgPSByZXNvbHZlUGF0aChjbG91ZEFzc2VtYmx5RGlyLCB3b3JraW5nRGlyZWN0b3J5KTtcblxuICAgIGlmICghY29tbWFuZERpZmYuZGlmZi5pbmNsdWRlcygne3N0YWNrU2VsZWN0b3J9JykpIHtcbiAgICAgIHRocm93IG5ldyBFcnJvcihgQ29tbWFuZCBmb3IgZGlmZiB3b3JrZmxvdyBtdXN0IGluY2x1ZGUge3N0YWNrU2VsZWN0b3J9IHBsYWNlaG9sZGVyLCBwcm92aWRlZDogJHtjb21tYW5kRGlmZi5kaWZmfWApO1xuICAgIH1cbiAgICBjb25zdCBzdGFja1NlbGVjdG9ycyA9IHN0ZXBTdGFja1NlbGVjdG9ycyhkaWZmQ29uZmlnLnN0YWNrU2VsZWN0b3IpO1xuXG4gICAgcHJpbnRDbG91ZEFzc2VtYmxpZXMucHVzaCh7XG4gICAgICBoZWFkZXI6IGBDREsgRGlmZiAtICR7Y29tbWFuZEtleX1gLFxuICAgICAgZGlyZWN0b3J5OiByZXNvbHZlZENsb3VkQXNzZW1ibHlEaXIsXG4gICAgfSk7XG4gICAgY29uc3QgbWF0cml4SW5jbHVkZXM6IHtcbiAgICAgICdqb2ItbmFtZSc6IHN0cmluZztcbiAgICAgICdjbG91ZC1hc3NlbWJseS1kaXJlY3RvcnknOiBzdHJpbmc7XG4gICAgICAnc3RhY2stc2VsZWN0b3ItcGF0dGVybnMnOiBzdHJpbmc7XG4gICAgICAnY29tbWFuZCc6IHN0cmluZztcbiAgICAgICdhc3N1bWUtcm9sZS1hcm4nOiBzdHJpbmc7XG4gICAgICAnYXNzdW1lLXJlZ2lvbic6IHN0cmluZztcbiAgICB9W10gPSBbXTtcbiAgICBmb3IgKGNvbnN0IHN0YWNrU2VsZWN0b3Igb2Ygc3RhY2tTZWxlY3RvcnMpIHtcbiAgICAgIG1hdHJpeEluY2x1ZGVzLnB1c2goe1xuICAgICAgICAnam9iLW5hbWUnOiBgRGlmZiAke2NvbW1hbmRLZXl9IC0gJHtzdGFja1NlbGVjdG9yLm5hbWV9YCxcbiAgICAgICAgJ2Nsb3VkLWFzc2VtYmx5LWRpcmVjdG9yeSc6IHJlc29sdmVkQ2xvdWRBc3NlbWJseURpcixcbiAgICAgICAgJ3N0YWNrLXNlbGVjdG9yLXBhdHRlcm5zJzogc3RhY2tTZWxlY3Rvci5zZWxlY3RvcixcbiAgICAgICAgJ2NvbW1hbmQnOiBjb21tYW5kRGlmZi5kaWZmLnJlcGxhY2UoJ3tzdGFja1NlbGVjdG9yfScsIHN0YWNrU2VsZWN0b3Iuc2VsZWN0b3IpLFxuICAgICAgICAnYXNzdW1lLXJvbGUtYXJuJzogZGlmZkNvbmZpZy5hc3N1bWVSb2xlQXJuLFxuICAgICAgICAnYXNzdW1lLXJlZ2lvbic6IGRpZmZDb25maWcuYXNzdW1lUmVnaW9uLFxuICAgICAgfSk7XG4gICAgfVxuXG4gICAgLy8gQHRzLWlnbm9yZVxuICAgIGpvYnNbJ3N5bnRoX18nICsgY29tbWFuZEtleV0gPSB7XG4gICAgICAnbmFtZSc6ICdTeW50aCAnICsgY29tbWFuZEtleSxcbiAgICAgICdydW5zLW9uJzogJ3VidW50dS1sYXRlc3QnLFxuICAgICAgJ3N0ZXBzJzogW1xuICAgICAgICBjaGVja291dFJlcG9TdGVwKCksXG4gICAgICAgIHtcbiAgICAgICAgICBuYW1lOiAnUnVuIENESyBFeHByZXNzIFBpcGVsaW5lIFN5bnRoJyxcbiAgICAgICAgICB1c2VzOiAnLi8uZ2l0aHViL2FjdGlvbnMvY2RrLWV4cHJlc3MtcGlwZWxpbmUtc3ludGgnLFxuICAgICAgICAgIHdpdGg6IHtcbiAgICAgICAgICAgICdjb21tYW5kJzogY29tbWFuZERpZmYuc3ludGgsXG4gICAgICAgICAgICAnY2xvdWQtYXNzZW1ibHktZGlyZWN0b3J5JzogcmVzb2x2ZWRDbG91ZEFzc2VtYmx5RGlyLFxuICAgICAgICAgICAgJ3dvcmtpbmctZGlyZWN0b3J5Jzogd29ya2luZ0RpcmVjdG9yeSB8fCAnLicsXG4gICAgICAgICAgfSxcbiAgICAgICAgfSxcbiAgICAgIF0sXG4gICAgfTtcbiAgICAvLyBAdHMtaWdub3JlXG4gICAgam9ic1snZGlmZl9fJyArIGNvbW1hbmRLZXldID0ge1xuICAgICAgJ25hbWUnOiAnJHt7IG1hdHJpeC5qb2ItbmFtZSB9fScsXG4gICAgICAnbmVlZHMnOiBbJ3N5bnRoX18nICsgY29tbWFuZEtleV0sXG4gICAgICAncnVucy1vbic6ICd1YnVudHUtbGF0ZXN0JyxcbiAgICAgICdwZXJtaXNzaW9ucyc6IHtcbiAgICAgICAgJ2FjdGlvbnMnOiAnd3JpdGUnLFxuICAgICAgICAnY29udGVudHMnOiAnd3JpdGUnLFxuICAgICAgICAnaWQtdG9rZW4nOiAnd3JpdGUnLFxuICAgICAgICAncHVsbC1yZXF1ZXN0cyc6ICd3cml0ZScsXG4gICAgICB9LFxuICAgICAgJ3N0cmF0ZWd5Jzoge1xuICAgICAgICAnbWF0cml4Jzoge1xuICAgICAgICAgIGluY2x1ZGU6IG1hdHJpeEluY2x1ZGVzLFxuICAgICAgICB9LFxuICAgICAgICAnZmFpbC1mYXN0JzogZmFsc2UsXG4gICAgICB9LFxuICAgICAgJ3N0ZXBzJzogW1xuICAgICAgICBjaGVja291dFJlcG9TdGVwKCksXG4gICAgICAgIC8vIHJlc3RvcmVCdWlsZENhY2hlU3RlcCgpLFxuICAgICAgICAvLyBhc3N1bWVBd3NSb2xlU3RlcChkaWZmQ29uZmlnLmFzc3VtZVJvbGVBcm4sIGRpZmZDb25maWcuYXNzdW1lUmVnaW9uKSxcbiAgICAgICAge1xuICAgICAgICAgIG5hbWU6ICdSdW4gQ0RLIEV4cHJlc3MgUGlwZWxpbmUgU3ludGgnLFxuICAgICAgICAgIHVzZXM6ICcuLy5naXRodWIvYWN0aW9ucy9jZGstZXhwcmVzcy1waXBlbGluZS1kaWZmJyxcbiAgICAgICAgICB3aXRoOiB7XG4gICAgICAgICAgICAnam9iLW5hbWUnOiAnJHt7IG1hdHJpeC5qb2ItbmFtZSB9fScsXG4gICAgICAgICAgICAnc3RhY2stc2VsZWN0b3ItcGF0dGVybnMnOiAnJHt7IG1hdHJpeC5zdGFjay1zZWxlY3Rvci1wYXR0ZXJucyB9fScsXG4gICAgICAgICAgICAnY2xvdWQtYXNzZW1ibHktZGlyZWN0b3J5JzogJyR7eyBtYXRyaXguY2xvdWQtYXNzZW1ibHktZGlyZWN0b3J5IH19JyxcbiAgICAgICAgICAgICdjb21tYW5kJzogJyR7eyBtYXRyaXguY29tbWFuZCB9fScsXG4gICAgICAgICAgICAnZ2l0aHViLXRva2VuJzogJyR7eyBzZWNyZXRzLkdJVEhVQl9UT0tFTiB9fScsXG4gICAgICAgICAgICAnYXNzdW1lLXJvbGUtYXJuJzogJyR7eyBtYXRyaXguYXNzdW1lLXJvbGUtYXJuIH19JyxcbiAgICAgICAgICAgICdhc3N1bWUtcmVnaW9uJzogJyR7eyBtYXRyaXguYXNzdW1lLXJlZ2lvbiB9fScsXG4gICAgICAgICAgfSxcbiAgICAgICAgfSxcbiAgICAgIF0sXG4gICAgfTtcbiAgfVxuXG4gIGNvbnN0IHdvcmtmbG93Q29udGVudCA9IG5ldyBHaXRodWJXb3JrZmxvdyh7XG4gICAgbmFtZTogYENESyBFeHByZXNzIFBpcGVsaW5lIERpZmYkeyhyZXF1aXJlc1VuaXF1ZUlkIHx8IGRpZmZDb25maWcuaWQpID8gJyAtICcrIGNhcGl0YWxpemVGaXJzdExldHRlcihkaWZmQ29uZmlnLmlkISkgOiAnJyB9YCxcbiAgICBvbjogZm9ybWF0V29ya2Zsb3dUcmlnZ2VycyhkaWZmQ29uZmlnLm9uKSxcbiAgICBqb2JzOiB7XG4gICAgICAuLi5qb2JzLFxuICAgICAgcHJpbnRfZGlmZjoge1xuICAgICAgICAnbmFtZSc6ICdQcmludCBEaWZmJyxcbiAgICAgICAgJ3J1bnMtb24nOiAndWJ1bnR1LWxhdGVzdCcsXG4gICAgICAgICdwZXJtaXNzaW9ucyc6IHtcbiAgICAgICAgICAnYWN0aW9ucyc6ICd3cml0ZScsXG4gICAgICAgICAgJ2NvbnRlbnRzJzogJ3dyaXRlJyxcbiAgICAgICAgICAnaWQtdG9rZW4nOiAnd3JpdGUnLFxuICAgICAgICAgICdwdWxsLXJlcXVlc3RzJzogJ3dyaXRlJyxcbiAgICAgICAgfSxcbiAgICAgICAgJ25lZWRzJzogT2JqZWN0LmtleXMoam9icykuZmlsdGVyKGogPT4gai5zdGFydHNXaXRoKCdkaWZmX18nKSksXG4gICAgICAgICdzdGVwcyc6IFtcbiAgICAgICAgICBjaGVja291dFJlcG9TdGVwKCksXG4gICAgICAgICAge1xuICAgICAgICAgICAgbmFtZTogJ1VwZGF0ZSBQUiBEZXNjcmlwdGlvbicsXG4gICAgICAgICAgICB1c2VzOiAncmVoYW52ZG0vY2RrLWV4cHJlc3MtcGlwZWxpbmUtZ2l0aHViLWRpZmZAdicrQ0RLX0VYUFJFU1NfUElQRUxJTkVfR0lUSFVCX0RJRkZfVkVSU0lPTixcbiAgICAgICAgICAgIHdpdGg6IHtcbiAgICAgICAgICAgICAgJ21vZGUnOiAncHJpbnQnLFxuICAgICAgICAgICAgICAnZ2l0aHViLXRva2VuJzogJyR7eyBzZWNyZXRzLkdJVEhVQl9UT0tFTiB9fScsXG4gICAgICAgICAgICAgICdjbG91ZC1hc3NlbWJsaWVzJzogSlNPTi5zdHJpbmdpZnkocHJpbnRDbG91ZEFzc2VtYmxpZXMpLFxuICAgICAgICAgICAgfSxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICB9LFxuICB9KTtcblxuICByZXR1cm4ge1xuICAgIGZpbGVOYW1lOiBgd29ya2Zsb3dzL2Nkay1leHByZXNzLXBpcGVsaW5lLWRpZmYkeyhyZXF1aXJlc1VuaXF1ZUlkIHx8IGRpZmZDb25maWcuaWQpID8gJy0nK2RpZmZDb25maWcuaWQhIDogJycgfS55bWxgLFxuICAgIGNvbnRlbnQ6IHdvcmtmbG93Q29udGVudCxcbiAgfTtcbn1cblxuZnVuY3Rpb24gZGVwbG95V29ya2Zsb3coZGVwbG95Q29uZmlnOiBEZXBsb3lXb3JrZmxvd0NvbmZpZywgd2F2ZXM6IElFeHByZXNzV2F2ZVtdLFxuICByZXF1aXJlc1VuaXF1ZUlkOiBib29sZWFuLCBnaXRodWJDb25maWc/OiBHaXRIdWJXb3JrZmxvd0NvbmZpZyk6IEdpdGh1YldvcmtmbG93RmlsZSB7XG5cbiAgZnVuY3Rpb24gZm9ybWF0V2F2ZUpvYklkKHdhdmU6IElFeHByZXNzV2F2ZSwgY29tbWFuZEtleTogc3RyaW5nKTogc3RyaW5nIHtcbiAgICByZXR1cm4gYGRlcGxveV9fJHtjb21tYW5kS2V5fV9fJHt3YXZlLmlkfWA7XG4gIH1cbiAgZnVuY3Rpb24gZm9ybWF0U3RhZ2VKb2JJZChzdGFnZTogSUV4cHJlc3NTdGFnZSwgY29tbWFuZEtleTogc3RyaW5nKTogc3RyaW5nIHtcbiAgICByZXR1cm4gYGRlcGxveV9fJHtjb21tYW5kS2V5fV9fXyR7c3RhZ2Uud2F2ZS5pZH0ke3N0YWdlLndhdmUuc2VwYXJhdG9yfSR7c3RhZ2UuaWR9YDtcbiAgfVxuICBmdW5jdGlvbiBmb3JtYXRTdGFja0pvYklkKHN0YWNrOiBJRXhwcmVzc1N0YWNrLCBjb21tYW5kS2V5OiBzdHJpbmcpOiBzdHJpbmcge1xuICAgIHJldHVybiBgZGVwbG95X18ke2NvbW1hbmRLZXl9X19fJHtzdGFjay5pZH1gO1xuICB9XG5cbiAgY29uc3Qgam9icyA9IHt9O1xuICBmb3IgKGxldCBbY29tbWFuZEtleSwgY29tbWFuZERlcGxveV0gb2YgT2JqZWN0LmVudHJpZXMoZGVwbG95Q29uZmlnLmNvbW1hbmRzKSkge1xuICAgIGNvbnN0IGNsb3VkQXNzZW1ibHlEaXJTeW50aCA9IGV4dHJhY3RBcmd1bWVudChjb21tYW5kRGVwbG95LnN5bnRoLCAnLS1vdXRwdXQnKSB8fCAnY2RrLm91dCc7XG4gICAgY29uc3QgY2xvdWRBc3NlbWJseURpciA9IGV4dHJhY3RBcmd1bWVudChjb21tYW5kRGVwbG95LmRlcGxveSwgJy0tYXBwJykgfHwgJ2Nkay5vdXQnO1xuICAgIGlmIChjbG91ZEFzc2VtYmx5RGlyU3ludGggIT09IGNsb3VkQXNzZW1ibHlEaXIpIHtcbiAgICAgIHRocm93IG5ldyBFcnJvcignVGhlIC0tb3V0cHV0IGFyZ3VtZW50IG9mIHN5bnRoIG11c3QgYmUgdGhlIHNhbWUgYXMgdGhlIC0tYXBwIGFyZ3VtZW50IGZvciBkZXBsb3knKTtcbiAgICB9XG4gICAgaWYgKCFjb21tYW5kRGVwbG95LmRlcGxveS5pbmNsdWRlcygne3N0YWNrU2VsZWN0b3J9JykpIHtcbiAgICAgIHRocm93IG5ldyBFcnJvcihgQ29tbWFuZCBmb3IgZGVwbG95IHdvcmtmbG93IG11c3QgaW5jbHVkZSB7c3RhY2tTZWxlY3Rvcn0gcGxhY2Vob2xkZXIsIHByb3ZpZGVkOiAke2NvbW1hbmREZXBsb3kuZGVwbG95fWApO1xuICAgIH1cblxuICAgIC8vIEdldCBhbmQgcmVzb2x2ZSB3b3JraW5nIGRpcmVjdG9yeVxuICAgIGNvbnN0IHdvcmtpbmdEaXJlY3RvcnkgPSBkZXBsb3lDb25maWcud29ya2luZ0RpcmVjdG9yeSB8fCBnaXRodWJDb25maWc/LndvcmtpbmdEaXJlY3Rvcnk7XG4gICAgY29uc3QgcmVzb2x2ZWRDbG91ZEFzc2VtYmx5RGlyID0gcmVzb2x2ZVBhdGgoY2xvdWRBc3NlbWJseURpciwgd29ya2luZ0RpcmVjdG9yeSk7XG5cbiAgICBjb25zdCBzeW50aEpvYklkID0gJ3N5bnRoX18nICsgY29tbWFuZEtleTtcbiAgICAvLyBAdHMtaWdub3JlXG4gICAgam9ic1tzeW50aEpvYklkXSA9IHtcbiAgICAgICduYW1lJzogJ1N5bnRoICcgKyBjb21tYW5kS2V5LFxuICAgICAgJ3J1bnMtb24nOiAndWJ1bnR1LWxhdGVzdCcsXG4gICAgICAnc3RlcHMnOiBbXG4gICAgICAgIGNoZWNrb3V0UmVwb1N0ZXAoKSxcbiAgICAgICAge1xuICAgICAgICAgIG5hbWU6ICdSdW4gQ0RLIEV4cHJlc3MgUGlwZWxpbmUgU3ludGgnLFxuICAgICAgICAgIHVzZXM6ICcuLy5naXRodWIvYWN0aW9ucy9jZGstZXhwcmVzcy1waXBlbGluZS1zeW50aCcsXG4gICAgICAgICAgd2l0aDoge1xuICAgICAgICAgICAgJ2NvbW1hbmQnOiBjb21tYW5kRGVwbG95LnN5bnRoLFxuICAgICAgICAgICAgJ2Nsb3VkLWFzc2VtYmx5LWRpcmVjdG9yeSc6IHJlc29sdmVkQ2xvdWRBc3NlbWJseURpcixcbiAgICAgICAgICAgICd3b3JraW5nLWRpcmVjdG9yeSc6IHdvcmtpbmdEaXJlY3RvcnkgfHwgJy4nLFxuICAgICAgICAgIH0sXG4gICAgICAgIH0sXG4gICAgICBdLFxuICAgIH07XG5cbiAgICAvLyBIYW5kbGUgZGlmZmVyZW50IGRlcGxveW1lbnQgc3RyYXRlZ2llcyBiYXNlZCBvbiBzdGFja1NlbGVjdG9yXG4gICAgaWYgKGRlcGxveUNvbmZpZy5zdGFja1NlbGVjdG9yID09PSAnd2F2ZScpIHtcbiAgICAgIGZvciAobGV0IHcgPSAwOyB3IDwgd2F2ZXMubGVuZ3RoOyB3KyspIHtcbiAgICAgICAgY29uc3Qgd2F2ZSA9IHdhdmVzW3ddO1xuICAgICAgICBjb25zdCB3YXZlSm9iSWQgPSBmb3JtYXRXYXZlSm9iSWQod2F2ZSwgY29tbWFuZEtleSk7XG5cbiAgICAgICAgY29uc3QgbmVlZHM6IHN0cmluZ1tdID0gW107XG4gICAgICAgIGlmICh3ID09IDApIHtcbiAgICAgICAgICBuZWVkcy5wdXNoKHN5bnRoSm9iSWQpO1xuICAgICAgICB9IGVsc2UgaWYgKHcgPiAwKSB7XG4gICAgICAgICAgY29uc3QgcHJldmlvdXNXYXZlSm9iSWQgPSBmb3JtYXRXYXZlSm9iSWQod2F2ZXNbdyAtIDFdLCBjb21tYW5kS2V5KTtcbiAgICAgICAgICBuZWVkcy5wdXNoKHByZXZpb3VzV2F2ZUpvYklkKTtcbiAgICAgICAgfVxuXG4gICAgICAgIC8vIEB0cy1pZ25vcmVcbiAgICAgICAgam9ic1t3YXZlSm9iSWRdID0ge1xuICAgICAgICAgICduYW1lJzogYFske2NvbW1hbmRLZXl9XSDwn4yKICR7d2F2ZS5pZH1gLFxuICAgICAgICAgICduZWVkcyc6IG5lZWRzLFxuICAgICAgICAgICdydW5zLW9uJzogJ3VidW50dS1sYXRlc3QnLFxuICAgICAgICAgICdwZXJtaXNzaW9ucyc6IHtcbiAgICAgICAgICAgICdhY3Rpb25zJzogJ3dyaXRlJyxcbiAgICAgICAgICAgICdjb250ZW50cyc6ICd3cml0ZScsXG4gICAgICAgICAgICAnaWQtdG9rZW4nOiAnd3JpdGUnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAgJ3N0ZXBzJzogW1xuICAgICAgICAgICAgY2hlY2tvdXRSZXBvU3RlcCgpLFxuICAgICAgICAgICAge1xuICAgICAgICAgICAgICBuYW1lOiAnUnVuIENESyBFeHByZXNzIFBpcGVsaW5lIERlcGxveScsXG4gICAgICAgICAgICAgIHVzZXM6ICcuLy5naXRodWIvYWN0aW9ucy9jZGstZXhwcmVzcy1waXBlbGluZS1kZXBsb3knLFxuICAgICAgICAgICAgICB3aXRoOiB7XG4gICAgICAgICAgICAgICAgJ3N0YWNrLXNlbGVjdG9yLXBhdHRlcm5zJzogYCR7d2F2ZS5pZH0ke3dhdmUuc2VwYXJhdG9yfSpgLFxuICAgICAgICAgICAgICAgICdjbG91ZC1hc3NlbWJseS1kaXJlY3RvcnknOiByZXNvbHZlZENsb3VkQXNzZW1ibHlEaXIsXG4gICAgICAgICAgICAgICAgJ2NvbW1hbmQnOiBjb21tYW5kRGVwbG95LmRlcGxveS5yZXBsYWNlKCd7c3RhY2tTZWxlY3Rvcn0nLCBgJHt3YXZlLmlkfSR7d2F2ZS5zZXBhcmF0b3J9KmApLFxuICAgICAgICAgICAgICAgICdhc3N1bWUtcm9sZS1hcm4nOiBkZXBsb3lDb25maWcuYXNzdW1lUm9sZUFybixcbiAgICAgICAgICAgICAgICAnYXNzdW1lLXJlZ2lvbic6IGRlcGxveUNvbmZpZy5hc3N1bWVSZWdpb24sXG4gICAgICAgICAgICAgICAgJ3dvcmtpbmctZGlyZWN0b3J5Jzogd29ya2luZ0RpcmVjdG9yeSB8fCAnLicsXG4gICAgICAgICAgICAgIH0sXG4gICAgICAgICAgICB9LFxuICAgICAgICAgIF0sXG4gICAgICAgIH07XG4gICAgICB9XG4gICAgfSBlbHNlIGlmIChkZXBsb3lDb25maWcuc3RhY2tTZWxlY3RvciA9PT0gJ3N0YWdlJykge1xuXG4gICAgICBmb3IgKGxldCB3ID0gMDsgdyA8IHdhdmVzLmxlbmd0aDsgdysrKSB7XG4gICAgICAgIGNvbnN0IHdhdmUgPSB3YXZlc1t3XTtcblxuICAgICAgICBmb3IgKGxldCBzID0gMDsgcyA8IHdhdmUuc3RhZ2VzLmxlbmd0aDsgcysrKSB7XG4gICAgICAgICAgY29uc3Qgc3RhZ2UgPSB3YXZlLnN0YWdlc1tzXTtcblxuICAgICAgICAgIGNvbnN0IHN0YWdlSm9iSWQgPSBmb3JtYXRTdGFnZUpvYklkKHN0YWdlLCBjb21tYW5kS2V5KTtcblxuICAgICAgICAgIGNvbnN0IG5lZWRzOiBzdHJpbmdbXSA9IFtdO1xuICAgICAgICAgIGlmICh3ID09IDApIHtcbiAgICAgICAgICAgIG5lZWRzLnB1c2goc3ludGhKb2JJZCk7XG4gICAgICAgICAgfSBlbHNlIGlmICh3ID4gMCkge1xuICAgICAgICAgICAgLy8gRWFjaCBzdGFnZSBqb2IgaW4gdGhpcyB3YXZlIG5lZWRzIHRvIGRlcGVuZCBvbiB0aGUgcHJldmlvdXMgd2F2ZSdzIHN0YWdlIGpvYnNcbiAgICAgICAgICAgIGZvciAoY29uc3Qgc1ByZXYgb2Ygd2F2ZXNbdyAtIDFdLnN0YWdlcykge1xuICAgICAgICAgICAgICBuZWVkcy5wdXNoKGZvcm1hdFN0YWdlSm9iSWQoc1ByZXYsIGNvbW1hbmRLZXkpKTtcbiAgICAgICAgICAgIH1cbiAgICAgICAgICB9XG5cbiAgICAgICAgICBpZiAod2F2ZS5zZXF1ZW50aWFsU3RhZ2VzICYmIHMgPiAwKSB7XG4gICAgICAgICAgICAvLyBFYWNoIHN0YWdlIGpvYiBuZWVkcyB0byBkZXBlbmQgb24gdGhlIHByZXZpb3VzIHN0YWdlIGpvYiBpbiB0aGUgc2FtZSB3YXZlXG4gICAgICAgICAgICBjb25zdCBwcmV2aW91c1N0YWdlSm9iSWQgPSBmb3JtYXRTdGFnZUpvYklkKHdhdmUuc3RhZ2VzW3MgLSAxXSwgY29tbWFuZEtleSk7XG4gICAgICAgICAgICBuZWVkcy5wdXNoKHByZXZpb3VzU3RhZ2VKb2JJZCk7XG4gICAgICAgICAgfVxuXG4gICAgICAgICAgLy8gQHRzLWlnbm9yZVxuICAgICAgICAgIGpvYnNbc3RhZ2VKb2JJZF0gPSB7XG4gICAgICAgICAgICAnbmFtZSc6IGBbJHtjb21tYW5kS2V5fV0g8J+PlyAke3dhdmUuaWR9JHt3YXZlLnNlcGFyYXRvcn0ke3N0YWdlLmlkfWAsXG4gICAgICAgICAgICAnbmVlZHMnOiBuZWVkcyxcbiAgICAgICAgICAgICdydW5zLW9uJzogJ3VidW50dS1sYXRlc3QnLFxuICAgICAgICAgICAgJ3Blcm1pc3Npb25zJzoge1xuICAgICAgICAgICAgICAnYWN0aW9ucyc6ICd3cml0ZScsXG4gICAgICAgICAgICAgICdjb250ZW50cyc6ICd3cml0ZScsXG4gICAgICAgICAgICAgICdpZC10b2tlbic6ICd3cml0ZScsXG4gICAgICAgICAgICB9LFxuICAgICAgICAgICAgJ3N0ZXBzJzogW1xuICAgICAgICAgICAgICBjaGVja291dFJlcG9TdGVwKCksXG4gICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICBuYW1lOiAnUnVuIENESyBFeHByZXNzIFBpcGVsaW5lIERlcGxveScsXG4gICAgICAgICAgICAgICAgdXNlczogJy4vLmdpdGh1Yi9hY3Rpb25zL2Nkay1leHByZXNzLXBpcGVsaW5lLWRlcGxveScsXG4gICAgICAgICAgICAgICAgd2l0aDoge1xuICAgICAgICAgICAgICAgICAgJ3N0YWNrLXNlbGVjdG9yLXBhdHRlcm5zJzogYCR7d2F2ZS5pZH0ke3dhdmUuc2VwYXJhdG9yfSR7c3RhZ2UuaWR9JHt3YXZlLnNlcGFyYXRvcn0qYCxcbiAgICAgICAgICAgICAgICAgICdjbG91ZC1hc3NlbWJseS1kaXJlY3RvcnknOiByZXNvbHZlZENsb3VkQXNzZW1ibHlEaXIsXG4gICAgICAgICAgICAgICAgICAnY29tbWFuZCc6IGNvbW1hbmREZXBsb3kuZGVwbG95LnJlcGxhY2UoJ3tzdGFja1NlbGVjdG9yfScsIGAke3dhdmUuaWR9JHt3YXZlLnNlcGFyYXRvcn0ke3N0YWdlLmlkfSR7d2F2ZS5zZXBhcmF0b3J9KmApLFxuICAgICAgICAgICAgICAgICAgJ2Fzc3VtZS1yb2xlLWFybic6IGRlcGxveUNvbmZpZy5hc3N1bWVSb2xlQXJuLFxuICAgICAgICAgICAgICAgICAgJ2Fzc3VtZS1yZWdpb24nOiBkZXBsb3lDb25maWcuYXNzdW1lUmVnaW9uLFxuICAgICAgICAgICAgICAgICAgJ3dvcmtpbmctZGlyZWN0b3J5Jzogd29ya2luZ0RpcmVjdG9yeSB8fCAnLicsXG4gICAgICAgICAgICAgICAgfSxcbiAgICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIF0sXG4gICAgICAgICAgfTtcbiAgICAgICAgfVxuICAgICAgfVxuXG4gICAgfSBlbHNlIGlmIChkZXBsb3lDb25maWcuc3RhY2tTZWxlY3RvciA9PT0gJ3N0YWNrJykge1xuXG4gICAgICBmb3IgKGxldCB3ID0gMDsgdyA8IHdhdmVzLmxlbmd0aDsgdysrKSB7XG4gICAgICAgIGNvbnN0IHdhdmUgPSB3YXZlc1t3XTtcblxuICAgICAgICBmb3IgKGxldCBzID0gMDsgcyA8IHdhdmUuc3RhZ2VzLmxlbmd0aDsgcysrKSB7XG4gICAgICAgICAgY29uc3Qgc3RhZ2UgPSB3YXZlLnN0YWdlc1tzXTtcblxuICAgICAgICAgIGZvciAobGV0IHN0ID0gMDsgc3QgPCBzdGFnZS5zdGFja3MubGVuZ3RoOyBzdCsrKSB7XG4gICAgICAgICAgICBjb25zdCBzdGFjayA9IHN0YWdlLnN0YWNrc1tzdF07XG5cbiAgICAgICAgICAgIGNvbnN0IHN0YWNrSm9iSWQgPSBmb3JtYXRTdGFja0pvYklkKHN0YWNrLCBjb21tYW5kS2V5KTtcblxuICAgICAgICAgICAgY29uc3QgbmVlZHM6IHN0cmluZ1tdID0gW107XG4gICAgICAgICAgICBpZiAodyA9PSAwKSB7XG4gICAgICAgICAgICAgIG5lZWRzLnB1c2goc3ludGhKb2JJZCk7XG4gICAgICAgICAgICB9IGVsc2UgaWYgKHcgPiAwKSB7XG4gICAgICAgICAgICAgIC8vIEVhY2ggc3RhY2sgam9iIGluIHRoaXMgd2F2ZSBuZWVkcyB0byBkZXBlbmQgb24gdGhlIHByZXZpb3VzIHdhdmUncyBzdGFjayBqb2JzXG4gICAgICAgICAgICAgIGZvciAoY29uc3Qgc1ByZXYgb2Ygd2F2ZXNbdyAtIDFdLnN0YWdlcykge1xuICAgICAgICAgICAgICAgIGZvciAoY29uc3Qgc3RQcmV2IG9mIHNQcmV2LnN0YWNrcykge1xuICAgICAgICAgICAgICAgICAgbmVlZHMucHVzaChmb3JtYXRTdGFja0pvYklkKHN0UHJldiwgY29tbWFuZEtleSkpO1xuICAgICAgICAgICAgICAgIH1cbiAgICAgICAgICAgICAgfVxuICAgICAgICAgICAgfVxuXG4gICAgICAgICAgICBpZiAod2F2ZS5zZXF1ZW50aWFsU3RhZ2VzICYmIHMgPiAwKSB7XG4gICAgICAgICAgICAgIC8vIEVhY2ggc3RhY2sgam9iIG5lZWRzIHRvIGRlcGVuZCBvbiB0aGUgcHJldmlvdXMgc3RhZ2UncyBzdGFjayBqb2JzIGluIHRoZSBzYW1lIHdhdmVcbiAgICAgICAgICAgICAgZm9yIChjb25zdCBzdFByZXYgb2Ygd2F2ZS5zdGFnZXNbcyAtIDFdLnN0YWNrcykge1xuICAgICAgICAgICAgICAgIG5lZWRzLnB1c2goZm9ybWF0U3RhY2tKb2JJZChzdFByZXYsIGNvbW1hbmRLZXkpKTtcbiAgICAgICAgICAgICAgfVxuICAgICAgICAgICAgfVxuXG4gICAgICAgICAgICAvLyBAdHMtaWdub3JlXG4gICAgICAgICAgICBqb2JzW3N0YWNrSm9iSWRdID0ge1xuICAgICAgICAgICAgICAnbmFtZSc6IGBbJHtjb21tYW5kS2V5fV0g8J+TpiAke3N0YWNrLmlkfWAsXG4gICAgICAgICAgICAgICduZWVkcyc6IG5lZWRzLFxuICAgICAgICAgICAgICAncnVucy1vbic6ICd1YnVudHUtbGF0ZXN0JyxcbiAgICAgICAgICAgICAgJ3Blcm1pc3Npb25zJzoge1xuICAgICAgICAgICAgICAgICdhY3Rpb25zJzogJ3dyaXRlJyxcbiAgICAgICAgICAgICAgICAnY29udGVudHMnOiAnd3JpdGUnLFxuICAgICAgICAgICAgICAgICdpZC10b2tlbic6ICd3cml0ZScsXG4gICAgICAgICAgICAgIH0sXG4gICAgICAgICAgICAgICdzdGVwcyc6IFtcbiAgICAgICAgICAgICAgICBjaGVja291dFJlcG9TdGVwKCksXG4gICAgICAgICAgICAgICAge1xuICAgICAgICAgICAgICAgICAgbmFtZTogJ1J1biBDREsgRXhwcmVzcyBQaXBlbGluZSBEZXBsb3knLFxuICAgICAgICAgICAgICAgICAgdXNlczogJy4vLmdpdGh1Yi9hY3Rpb25zL2Nkay1leHByZXNzLXBpcGVsaW5lLWRlcGxveScsXG4gICAgICAgICAgICAgICAgICB3aXRoOiB7XG4gICAgICAgICAgICAgICAgICAgICdzdGFjay1zZWxlY3Rvci1wYXR0ZXJucyc6IHN0YWNrLmlkLFxuICAgICAgICAgICAgICAgICAgICAnY2xvdWQtYXNzZW1ibHktZGlyZWN0b3J5JzogcmVzb2x2ZWRDbG91ZEFzc2VtYmx5RGlyLFxuICAgICAgICAgICAgICAgICAgICAnY29tbWFuZCc6IGNvbW1hbmREZXBsb3kuZGVwbG95LnJlcGxhY2UoJ3tzdGFja1NlbGVjdG9yfScsIHN0YWNrLmlkKSxcbiAgICAgICAgICAgICAgICAgICAgJ2Fzc3VtZS1yb2xlLWFybic6IGRlcGxveUNvbmZpZy5hc3N1bWVSb2xlQXJuLFxuICAgICAgICAgICAgICAgICAgICAnYXNzdW1lLXJlZ2lvbic6IGRlcGxveUNvbmZpZy5hc3N1bWVSZWdpb24sXG4gICAgICAgICAgICAgICAgICAgICd3b3JraW5nLWRpcmVjdG9yeSc6IHdvcmtpbmdEaXJlY3RvcnkgfHwgJy4nLFxuICAgICAgICAgICAgICAgICAgfSxcbiAgICAgICAgICAgICAgICB9LFxuICAgICAgICAgICAgICBdLFxuICAgICAgICAgICAgfTtcbiAgICAgICAgICB9XG4gICAgICAgIH1cbiAgICAgIH1cblxuICAgIH1cbiAgfVxuXG4gIGNvbnN0IHdvcmtmbG93Q29udGVudCA9IG5ldyBHaXRodWJXb3JrZmxvdyh7XG4gICAgbmFtZTogYENESyBFeHByZXNzIFBpcGVsaW5lIERlcGxveSR7KHJlcXVpcmVzVW5pcXVlSWQgfHwgZGVwbG95Q29uZmlnLmlkKSA/ICcgLSAnKyBjYXBpdGFsaXplRmlyc3RMZXR0ZXIoZGVwbG95Q29uZmlnLmlkISkgOiAnJyB9YCxcbiAgICBjb25jdXJyZW5jeToge1xuICAgICAgJ2dyb3VwJzogYGNkay1leHByZXNzLXBpcGVsaW5lLWRlcGxveSR7KHJlcXVpcmVzVW5pcXVlSWQgfHwgZGVwbG95Q29uZmlnLmlkKSA/ICctJytkZXBsb3lDb25maWcuaWQhIDogJycgfWAsXG4gICAgICAnY2FuY2VsLWluLXByb2dyZXNzJzogZmFsc2UsXG4gICAgfSxcbiAgICBvbjogZm9ybWF0V29ya2Zsb3dUcmlnZ2VycyhkZXBsb3lDb25maWcub24pLFxuICAgIGpvYnM6IHtcbiAgICAgIC4uLmpvYnMsXG4gICAgfSxcbiAgfSk7XG5cbiAgcmV0dXJuIHtcbiAgICBmaWxlTmFtZTogYHdvcmtmbG93cy9jZGstZXhwcmVzcy1waXBlbGluZS1kZXBsb3kkeyhyZXF1aXJlc1VuaXF1ZUlkIHx8IGRlcGxveUNvbmZpZy5pZCkgPyAnLScrZGVwbG95Q29uZmlnLmlkISA6ICcnIH0ueW1sYCxcbiAgICBjb250ZW50OiB3b3JrZmxvd0NvbnRlbnQsXG4gIH07XG59XG5cbiJdfQ==