import * as fs from 'fs';
import * as path from 'path';
import { GHAStage } from './gha-stage';

export interface GHAWorkflowConfig {
  /** Directory to write workflow files @default .github/workflows */
  readonly outputDir?: string;
  /** AWS region for CDK operations */
  readonly awsRegion: string;
  /** IAM role ARN to assume for deployments (OIDC) */
  readonly deployRoleArn: string;
  /** IAM role ARN for Bedrock analysis @default same as deployRoleArn */
  readonly bedrockRoleArn?: string;
  /** Bedrock region @default us-east-1 */
  readonly bedrockRegion?: string;
  /** Node.js version @default 22 */
  readonly nodeVersion?: string;
  /** Install command @default yarn install --frozen-lockfile */
  readonly installCommand?: string;
  /** Synth command @default npx cdk synth */
  readonly synthCommand?: string;
  /** Branch that triggers deploy @default main */
  readonly deployBranch?: string;
  /** Enable Bedrock analysis on PRs @default true */
  readonly enableBedrockAnalysis?: boolean;
  /** Concurrency for cdk deploy @default 5 */
  readonly deployConcurrency?: number;
  /** Which stage to diff on PRs @default first stage (index 0) */
  readonly diffStageIndex?: number;
  /** Path filters for triggering deploy and PR review workflows. If set, workflows only trigger on changes matching these paths (e.g. ['src/**', 'package.json']). */
  readonly triggerDeployPaths?: string[];
}

const ACTIONS_VERSION = 'v6';

/**
 * Generate GitHub Actions workflows for the pipeline.
 */
export function generateWorkflows(stages: GHAStage[], config: GHAWorkflowConfig): void {
  const outputDir = config.outputDir || '.github/workflows';
  fs.mkdirSync(outputDir, { recursive: true });

  fs.writeFileSync(path.join(outputDir, 'pr-review.yml'), buildPRWorkflow(stages, config));
  fs.writeFileSync(path.join(outputDir, 'deploy.yml'), buildDeployWorkflow(stages, config));
}

function buildPathsBlock(config: GHAWorkflowConfig): string[] {
  if (!config.triggerDeployPaths || config.triggerDeployPaths.length === 0) {
    return [];
  }
  const result: string[] = ['    paths:'];
  for (const p of config.triggerDeployPaths) {
    result.push('      - \'' + p + '\'');
  }
  return result;
}

function buildPRWorkflow(stages: GHAStage[], config: GHAWorkflowConfig): string {
  const nodeVersion = config.nodeVersion || '22';
  const installCmd = config.installCommand || 'yarn install --frozen-lockfile';
  const synthCmd = config.synthCommand || 'npx cdk synth';
  const bedrockRegion = config.bedrockRegion || 'us-east-1';
  const bedrockRoleArn = config.bedrockRoleArn || config.deployRoleArn;
  const enableBedrock = config.enableBedrockAnalysis !== false;
  const branch = config.deployBranch || 'main';

  const diffStageIdx = config.diffStageIndex ?? 1;
  const diffStage = stages[diffStageIdx] || stages[0];
  const diffStackNames = diffStage.allStacks().map(st => st.stackName);

  const diffSteps = diffStackNames.map(name =>
    [
      '          DIFF_OUTPUT=$(npx cdk diff ' + name + ' --exclusively 2>&1 || true)',
      '          if echo "$DIFF_OUTPUT" | grep -q "There were differences"; then',
      '            HAS_CHANGES=true',
      '            echo "$DIFF_OUTPUT" > "cdk.out/diffs/' + name + '.diff"',
      '          fi',
    ].join('\n'),
  ).join('\n');

  const lines: string[] = [
    '# ~~ Generated by @raindancers/agentl. To modify, edit your CDK app and run "npx cdk synth".',
    'name: PR Review - Diff & Analysis',
    '',
    'on:',
    '  pull_request:',
    '    branches: [' + branch + ']',
    ...buildPathsBlock(config),
    '',
    'permissions:',
    '  id-token: write',
    '  contents: read',
    '  pull-requests: write',
    '',
    'jobs:',
    '  review:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@' + ACTIONS_VERSION,
    '',
    '      - uses: actions/setup-node@' + ACTIONS_VERSION,
    '        with:',
    '          node-version: \'' + nodeVersion + '\'',
    '          cache: yarn',
    '',
    '      - run: ' + installCmd,
    '',
    '      - uses: aws-actions/configure-aws-credentials@v4',
    '        with:',
    '          role-to-assume: ' + config.deployRoleArn,
    '          aws-region: ' + config.awsRegion,
    '',
    '      - name: CDK Synth',
    '        run: ' + synthCmd,
    '',
    '      - name: CDK Diff (' + diffStage.id + ')',
    '        id: diff',
    '        run: |',
    '          mkdir -p cdk.out/diffs',
    '          HAS_CHANGES=false',
    diffSteps,
    '          echo "has_changes=$HAS_CHANGES" >> $GITHUB_OUTPUT',
    '',
    '      - name: Generate Diff Summary',
    '        if: steps.diff.outputs.has_changes == \'true\'',
    '        run: |',
    '          echo "## 📋 CDK Diff Summary (' + diffStage.id + ')" > cdk.out/diffs/comment.md',
    '          echo "" >> cdk.out/diffs/comment.md',
    '          for f in cdk.out/diffs/*.diff; do',
    '            [ -f "$f" ] || continue',
    '            STACK=$(basename "$f" .diff)',
    '            echo "<details>" >> cdk.out/diffs/comment.md',
    '            echo "<summary>📦 $STACK</summary>" >> cdk.out/diffs/comment.md',
    '            echo "" >> cdk.out/diffs/comment.md',
    '            echo \'```diff\' >> cdk.out/diffs/comment.md',
    '            cat "$f" >> cdk.out/diffs/comment.md',
    '            echo \'```\' >> cdk.out/diffs/comment.md',
    '            echo "</details>" >> cdk.out/diffs/comment.md',
    '            echo "" >> cdk.out/diffs/comment.md',
    '          done',
  ];

  if (enableBedrock) {
    lines.push(
      '',
      '      - uses: aws-actions/configure-aws-credentials@v4',
      '        if: steps.diff.outputs.has_changes == \'true\'',
      '        with:',
      '          role-to-assume: ' + bedrockRoleArn,
      '          aws-region: ' + bedrockRegion,
      '',
      '      - name: Well-Architected Analysis',
      '        if: steps.diff.outputs.has_changes == \'true\'',
      '        run: |',
      '          npx agentl analyze --output cdk.out/diffs/analysis.md',
      '          cat cdk.out/diffs/analysis.md >> cdk.out/diffs/comment.md',
    );
  }

  lines.push(
    '',
    '      - name: Post PR Comment',
    '        if: steps.diff.outputs.has_changes == \'true\'',
    '        uses: marocchino/sticky-pull-request-comment@v2',
    '        with:',
    '          path: cdk.out/diffs/comment.md',
  );

  return lines.join('\n') + '\n';
}

function buildDeployWorkflow(stages: GHAStage[], config: GHAWorkflowConfig): string {
  const nodeVersion = config.nodeVersion || '22';
  const installCmd = config.installCommand || 'yarn install --frozen-lockfile';
  const synthCmd = config.synthCommand || 'npx cdk synth';
  const concurrency = config.deployConcurrency || 5;
  const branch = config.deployBranch || 'main';

  const lines: string[] = [
    '# ~~ Generated by @raindancers/agentl. To modify, edit your CDK app and run "npx cdk synth".',
    'name: Deploy',
    '',
    'on:',
    '  push:',
    '    branches: [' + branch + ']',
    ...buildPathsBlock(config),
    '',
    'permissions:',
    '  id-token: write',
    '  contents: read',
    '',
    'concurrency:',
    '  group: deploy',
    '  cancel-in-progress: false',
    '',
    'jobs:',
    '  synth:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@' + ACTIONS_VERSION,
    '',
    '      - uses: actions/setup-node@' + ACTIONS_VERSION,
    '        with:',
    '          node-version: \'' + nodeVersion + '\'',
    '          cache: yarn',
    '',
    '      - run: ' + installCmd,
    '',
    '      - uses: aws-actions/configure-aws-credentials@v4',
    '        with:',
    '          role-to-assume: ' + config.deployRoleArn,
    '          aws-region: ' + config.awsRegion,
    '',
    '      - name: CDK Synth',
    '        run: ' + synthCmd,
    '',
    '      - uses: actions/upload-artifact@v4',
    '        with:',
    '          name: cdk-out',
    '          path: cdk.out/',
  ];

  let previousJobId = 'synth';

  for (let s = 0; s < stages.length; s++) {
    const stage = stages[s];
    const stageJobId = 'deploy_' + stage.id;

    const deploySteps: string[] = [];
    for (const wave of stage.waves) {
      const stacks = wave.stacks.map(e => e.stack.stackName).join(' ');
      deploySteps.push(
        '',
        '      - name: "🌊 ' + wave.id + '"',
        '        run: npx cdk deploy ' + stacks + ' --require-approval never --concurrency ' + concurrency + ' --app cdk.out/',
      );
    }

    lines.push(
      '',
      '  ' + stageJobId + ':',
      '    name: "🚀 ' + stage.id + '"',
      '    runs-on: ubuntu-latest',
      '    needs: ' + previousJobId,
    );

    if (stage.environment) {
      lines.push('    environment: ' + stage.environment);
    }

    lines.push(
      '    steps:',
      '      - uses: actions/checkout@' + ACTIONS_VERSION,
      '',
      '      - uses: actions/setup-node@' + ACTIONS_VERSION,
      '        with:',
      '          node-version: \'' + nodeVersion + '\'',
      '          cache: yarn',
      '',
      '      - run: ' + installCmd,
      '',
      '      - uses: actions/download-artifact@v4',
      '        with:',
      '          name: cdk-out',
      '          path: cdk.out/',
      '',
      '      - uses: aws-actions/configure-aws-credentials@v4',
      '        with:',
      '          role-to-assume: ' + config.deployRoleArn,
      '          aws-region: ' + config.awsRegion,
      ...deploySteps,
    );

    previousJobId = stageJobId;
  }

  return lines.join('\n') + '\n';
}
