import * as fs from 'fs';
import * as path from 'path';
import { RunnerSize } from './shared';

export interface GHACodeBuildTriggerConfig {
  /** Name of the workflow (appears in GitHub Actions UI) */
  readonly workflowName: string;
  /** Filename for the workflow (e.g. 'publish-docs.yml') */
  readonly workflowFileName: string;
  /** Path filters that trigger this workflow (e.g. ['publish/**', 'mkdocs.yml']) */
  readonly triggerPaths: string[];
  /** Branch that triggers the workflow @default main */
  readonly deployBranch?: string;
  /** AWS region where the CodeBuild project lives */
  readonly awsRegion: string;
  /** IAM role ARN to assume via GitHub OIDC */
  readonly deployRoleArn: string;
  /** Name of the CodeBuild project to trigger */
  readonly codeBuildProjectName: string;
  /** Directory to write workflow files @default .github/workflows */
  readonly outputDir?: string;
  /** GitHub Actions runner size @default RunnerSize.STANDARD (2 cores) */
  readonly runnerSize?: RunnerSize;
}

/**
 * Generates a GitHub Actions workflow that triggers an AWS CodeBuild project
 * when specified file paths change on push to a branch.
 */
export function generateCodeBuildTriggerWorkflow(config: GHACodeBuildTriggerConfig): void {
  const outputDir = config.outputDir || '.github/workflows';
  fs.mkdirSync(outputDir, { recursive: true });

  const content = buildCodeBuildTriggerWorkflow(config);
  fs.writeFileSync(path.join(outputDir, config.workflowFileName), content);
}

function buildCodeBuildTriggerWorkflow(config: GHACodeBuildTriggerConfig): string {
  const branch = config.deployBranch || 'main';
  const runsOn = config.runnerSize || RunnerSize.STANDARD;

  const lines: string[] = [
    '# ~~ Generated by @raindancers/agentl. To modify, edit your CDK app and run "npx cdk synth".',
    'name: ' + config.workflowName,
    '',
    'on:',
    '  push:',
    '    branches: [' + branch + ']',
    '    paths:',
  ];

  for (const p of config.triggerPaths) {
    lines.push('      - \'' + p + '\'');
  }

  lines.push(
    '',
    'permissions:',
    '  id-token: write',
    '  contents: read',
    '',
    'jobs:',
    '  trigger:',
    '    runs-on: ' + runsOn,
    '    steps:',
    '      - name: Configure AWS credentials',
    '        uses: aws-actions/configure-aws-credentials@v4',
    '        with:',
    '          role-to-assume: ' + config.deployRoleArn,
    '          aws-region: ' + config.awsRegion,
    '',
    '      - name: Trigger CodeBuild',
    '        run: aws codebuild start-build --project-name ' + config.codeBuildProjectName + ' --region ' + config.awsRegion,
  );

  return lines.join('\n') + '\n';
}
